version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
    groups:
      actions-non-major:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: nuget
    directory: /
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    groups:
      nuget-non-major:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: /site
    schedule:
      interval: daily
    groups:
      npm-non-major:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
