namespace SQLite.Framework;

/// <summary>
/// Binds the value of a single column on <paramref name="entity" /> to <paramref name="parameterIndex" />
/// on a prepared <c>INSERT</c> / <c>UPDATE</c> / <c>DELETE</c> statement. Generated by
/// <c>SQLite.Framework.SourceGenerator</c> per writable property and registered into
/// <see cref="SQLiteOptions.EntityWriters" />.
/// </summary>
/// <param name="statement">The prepared SQLite statement.</param>
/// <param name="parameterIndex">The 1-based parameter index to bind to.</param>
/// <param name="entity">The entity to read the column value from. The implementation casts to the concrete type.</param>
/// <param name="options">The active database options. Used so generated code can reach storage-mode and converter settings.</param>
public delegate void SQLiteEntityColumnWriter(sqlite3_stmt statement, int parameterIndex, object entity, SQLiteOptions options);
