using System.Text;
using Microsoft.CodeAnalysis;
using SQLite.Framework.SourceGenerator.Enums;
using SQLite.Framework.SourceGenerator.Models;

namespace SQLite.Framework.SourceGenerator.Helpers;

/// <summary>
/// Writes one method per entity and one method per Select result, plus the
/// <c>UseGeneratedMaterializers</c> extension that adds them to a builder.
/// </summary>
public static class EntityMaterializerEmitter
{
    /// <summary>
    /// Builds the generated source that holds all entity and select materializers.
    /// </summary>
    public static string Emit(string rootNamespace, IEnumerable<INamedTypeSymbol> entities, IEnumerable<SelectInvocation> selects, IEnumerable<(GroupByKeyInvocation Invocation, SemanticModel Model)> groupKeys, HashSet<(INamedTypeSymbol, string)> nestedInitSet)
    {
        HashSet<INamedTypeSymbol> entitySet = new(entities, SymbolEqualityComparer.Default);

        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS8600, CS8601, CS8602, CS8603, CS8604, CS8605, CS8629");
        sb.AppendLine("#pragma warning disable IL2026, IL2057, IL2067, IL2070, IL2072, IL2075, IL2077, IL2080, IL2087, IL2090");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Reflection;");
        sb.AppendLine("using SQLitePCL;");
        sb.AppendLine("using SQLite.Framework;");
        sb.AppendLine("using SQLite.Framework.Enums;");
        sb.AppendLine("using SQLite.Framework.Internals.Models;");
        sb.AppendLine();
        sb.Append("namespace ").AppendLine(rootNamespace);
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Generated entity and select materializers. Populated onto a builder via <see cref=\"SQLiteFrameworkGeneratedMaterializers.UseGeneratedMaterializers\"/>.</summary>");
        sb.AppendLine("    internal static class SQLiteFrameworkGeneratedMaterializers");
        sb.AppendLine("    {");
        sb.AppendLine("        private static int FindColumnIndex(global::System.Collections.Generic.Dictionary<string, int> columns, string name)");
        sb.AppendLine("        {");
        sb.AppendLine("            if (columns.TryGetValue(name, out int idx)) { return idx; }");
        sb.AppendLine("            foreach (global::System.Collections.Generic.KeyValuePair<string, int> column in columns)");
        sb.AppendLine("            {");
        sb.AppendLine("                if (string.Equals(column.Key, name, global::System.StringComparison.OrdinalIgnoreCase)) { return column.Value; }");
        sb.AppendLine("            }");
        sb.AppendLine("            return -1;");
        sb.AppendLine("        }");
        sb.AppendLine();
        sb.AppendLine("        /// <summary>Registers every emitted materializer onto <paramref name=\"builder\"/>.</summary>");
        sb.AppendLine("        internal static SQLiteOptionsBuilder UseGeneratedMaterializers(this SQLiteOptionsBuilder builder)");
        sb.AppendLine("        {");

        List<(INamedTypeSymbol Symbol, string MethodName, EmitStrategy Strategy)> emittedEntities = new();
        int index = 0;
        foreach (INamedTypeSymbol entity in entitySet)
        {
            if (!TryGetEmitStrategy(entity, out EmitStrategy strategy))
            {
                continue;
            }

            string methodName = $"Materialize_{SanitizeIdentifier(entity.Name)}_{index++}";
            emittedEntities.Add((entity, methodName, strategy));

            switch (strategy)
            {
                case EmitStrategy.Direct:
                    sb.Append("            builder.EntityMaterializers[typeof(").Append(entity.ToDisplayString()).Append(")] = ").Append(methodName).AppendLine(";");
                    EntityColumnWriterEmitter.EmitRegistration(sb, entity, methodName);
                    break;
                case EmitStrategy.Reflection:
                {
                    string typeField = $"s_type_{methodName}";
                    sb.Append("            builder.EntityMaterializers[").Append(typeField).Append("] = ").Append(methodName).AppendLine(";");
                    break;
                }
                case EmitStrategy.Anonymous:
                {
                    string typeField = $"s_type_{methodName}";
                    sb.Append("            builder.EntityMaterializers[").Append(typeField).Append("] = ").Append(methodName).AppendLine(";");
                    break;
                }
                case EmitStrategy.Positional:
                {
                    sb.Append("            builder.EntityMaterializers[typeof(").Append(entity.ToDisplayString()).Append(")] = ").Append(methodName).AppendLine(";");
                    break;
                }
                case EmitStrategy.PositionalReflection:
                {
                    string typeField = $"s_type_{methodName}";
                    sb.Append("            builder.EntityMaterializers[").Append(typeField).Append("] = ").Append(methodName).AppendLine(";");
                    break;
                }
            }
        }

        StringBuilder selectBodies = new();
        int selectIndex = 0;
        foreach (SelectInvocation sel in selects)
        {
            string methodName = $"Select_{SanitizeIdentifier(sel.ProjectionType.Name)}_{selectIndex}";
            StringBuilder trial = new();
            bool emitted;
            try
            {
                emitted = SelectMaterializerEmitter.TryEmit(trial, methodName, sel.Body, sel.WriterCtx);
            }
            catch
            {
                emitted = false;
            }

            if (emitted)
            {
                selectBodies.Append(trial);
                sb.Append("            builder.SelectMaterializers[")
                    .Append(EscapeStringLiteral(sel.Signature))
                    .Append("] = ").Append(methodName).AppendLine(";");
                selectIndex++;
            }
        }

        StringBuilder groupKeyBodies = new();
        int groupKeyIndex = 0;
        HashSet<string> emittedGroupingTypes = new();
        foreach ((GroupByKeyInvocation invocation, SemanticModel model) in groupKeys)
        {
            string methodName = $"GroupKey_{SanitizeIdentifier(invocation.KeyType.Name)}_{groupKeyIndex}";
            StringBuilder trial = new();
            bool emitted;
            try
            {
                emitted = GroupByKeyMaterializerEmitter.TryEmit(trial, methodName, invocation, model);
            }
            catch
            {
                emitted = false;
            }

            if (emitted)
            {
                groupKeyBodies.Append(trial);
                sb.Append("            builder.GroupByKeyMaterializers[")
                    .Append(EscapeStringLiteral(invocation.Signature))
                    .Append("] = ").Append(methodName).AppendLine(";");
                groupKeyIndex++;

                if (CanEmitGroupingMaterializer(invocation))
                {
                    string keyDisplay = invocation.KeyType.ToDisplayString();
                    string elementDisplay = invocation.ParameterType.ToDisplayString();
                    if (emittedGroupingTypes.Add(keyDisplay + "|" + elementDisplay))
                    {
                        sb.Append("            builder.GroupingQueryMaterializers[typeof(global::System.Linq.IGrouping<")
                            .Append(keyDisplay).Append(", ").Append(elementDisplay)
                            .Append(">)] = static (db, expr) => db.ExecuteGeneratedGroupingQuery<")
                            .Append(keyDisplay).Append(", ").Append(elementDisplay)
                            .AppendLine(">(expr);");
                    }
                }
            }
        }

        sb.AppendLine("            return builder;");
        sb.AppendLine("        }");
        sb.AppendLine();

        foreach ((INamedTypeSymbol entity, string methodName, EmitStrategy strategy) in emittedEntities)
        {
            switch (strategy)
            {
                case EmitStrategy.Direct:
                    EmitMaterializer(sb, entity, methodName, entitySet, nestedInitSet);
                    EntityColumnWriterEmitter.EmitWriters(sb, entity, methodName);
                    break;
                case EmitStrategy.Reflection:
                    EmitReflectionMaterializer(sb, entity, methodName, entitySet, nestedInitSet);
                    break;
                case EmitStrategy.Anonymous:
                    EmitAnonymousMaterializer(sb, entity, methodName, entitySet, nestedInitSet);
                    break;
                case EmitStrategy.Positional:
                    EmitPositionalMaterializer(sb, entity, methodName);
                    break;
                case EmitStrategy.PositionalReflection:
                    EmitPositionalReflectionMaterializer(sb, entity, methodName);
                    break;
            }
        }

        sb.Append(selectBodies);
        sb.Append(groupKeyBodies);

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string EscapeStringLiteral(string value)
    {
        StringBuilder sb = new(value.Length + 2);
        sb.Append('"');
        foreach (char c in value)
        {
            switch (c)
            {
                case '\\': sb.Append("\\\\"); break;
                case '"': sb.Append("\\\""); break;
                case '\n': sb.Append("\\n"); break;
                case '\r': sb.Append("\\r"); break;
                case '\t': sb.Append("\\t"); break;
                default: sb.Append(c); break;
            }
        }
        sb.Append('"');
        return sb.ToString();
    }

    private static bool TryGetEmitStrategy(INamedTypeSymbol entity, out EmitStrategy strategy)
    {
        strategy = EmitStrategy.Direct;

        if (entity.IsAbstract || entity.IsStatic
            || (entity.TypeKind != TypeKind.Class && entity.TypeKind != TypeKind.Struct))
        {
            return false;
        }

        if (entity.IsValueType)
        {
            IMethodSymbol? structPositional = TryFindPositionalConstructor(entity);
            if (structPositional == null || !IsReachableFromGeneratedCode(entity))
            {
                return false;
            }

            foreach (IParameterSymbol parameter in structPositional.Parameters)
            {
                if (!IsEmittablePropertyType(parameter.Type) || !IsReachableFromGeneratedCode(parameter.Type))
                {
                    return false;
                }
            }

            strategy = ArePositionalExtrasAssignable(entity, structPositional) ? EmitStrategy.Positional : EmitStrategy.PositionalReflection;
            return true;
        }

        if (entity.IsAnonymousType)
        {
            foreach (IPropertySymbol anonProp in entity.GetMembers().OfType<IPropertySymbol>())
            {
                if (!IsEmittablePropertyType(anonProp.Type))
                {
                    return false;
                }
                ITypeSymbol stripped = StripNullableSymbol(anonProp.Type);
                if (!IsReachableFromGeneratedCode(stripped))
                {
                    return false;
                }
            }

            strategy = EmitStrategy.Anonymous;
            return true;
        }

        bool hasAnyParameterlessCtor = false;
        bool hasPublicParameterlessCtor = false;
        foreach (IMethodSymbol ctor in entity.InstanceConstructors)
        {
            if (ctor.Parameters.Length == 0)
            {
                hasAnyParameterlessCtor = true;
                if (ctor.DeclaredAccessibility == Accessibility.Public)
                {
                    hasPublicParameterlessCtor = true;
                }
            }
        }

        if (!hasAnyParameterlessCtor)
        {
            IMethodSymbol? positional = TryFindPositionalConstructor(entity);
            if (positional == null)
            {
                return false;
            }

            foreach (IParameterSymbol parameter in positional.Parameters)
            {
                if (!IsEmittablePropertyType(parameter.Type))
                {
                    return false;
                }
            }

            bool membersReachable = positional.Parameters.All(p => IsReachableFromGeneratedCode(p.Type))
                && EnumerateInstanceProperties(entity)
                    .Where(p => p.DeclaredAccessibility == Accessibility.Public && p.SetMethod != null)
                    .All(p => IsReachableFromGeneratedCode(p.Type) && IsEmittablePropertyType(p.Type));

            if (!membersReachable)
            {
                return false;
            }

            strategy = IsReachableFromGeneratedCode(entity) && ArePositionalExtrasAssignable(entity, positional)
                ? EmitStrategy.Positional
                : EmitStrategy.PositionalReflection;
            return true;
        }

        bool canNameEntity = IsReachableFromGeneratedCode(entity);
        bool anyPropNeedsReflection = false;

        foreach (IPropertySymbol prop in EnumerateInstanceProperties(entity))
        {
            if (prop.SetMethod == null)
            {
                continue;
            }

            ITypeSymbol propType = prop.Type;
            if (!IsEmittablePropertyType(propType))
            {
                return false;
            }

            if (!IsReachableFromGeneratedCode(propType))
            {
                anyPropNeedsReflection = true;
            }

            if (prop.DeclaredAccessibility == Accessibility.Public && !IsSetterAccessibleFromGeneratedCode(prop))
            {
                anyPropNeedsReflection = true;
            }
        }

        strategy = (!canNameEntity || !hasPublicParameterlessCtor || anyPropNeedsReflection)
            ? EmitStrategy.Reflection
            : EmitStrategy.Direct;
        return true;
    }

    private static bool HasPublicParameterlessConstructor(INamedTypeSymbol entity)
    {
        foreach (IMethodSymbol ctor in entity.InstanceConstructors)
        {
            if (ctor.Parameters.Length == 0 && ctor.DeclaredAccessibility == Accessibility.Public)
            {
                return true;
            }
        }

        return false;
    }

    private static bool IsSetterAccessibleFromGeneratedCode(IPropertySymbol prop)
    {
        return prop.SetMethod == null
            || prop.SetMethod.DeclaredAccessibility is Accessibility.Public
                or Accessibility.Internal
                or Accessibility.ProtectedOrInternal
                or Accessibility.NotApplicable;
    }

    private static bool ArePositionalExtrasAssignable(INamedTypeSymbol entity, IMethodSymbol ctor)
    {
        HashSet<string> ctorParameterNames = new(StringComparer.OrdinalIgnoreCase);
        foreach (IParameterSymbol parameter in ctor.Parameters)
        {
            ctorParameterNames.Add(parameter.Name);
        }

        foreach (IPropertySymbol prop in EnumerateInstanceProperties(entity))
        {
            if (prop.DeclaredAccessibility != Accessibility.Public || prop.SetMethod == null || ctorParameterNames.Contains(prop.Name))
            {
                continue;
            }

            if (!IsSetterAccessibleFromGeneratedCode(prop))
            {
                return false;
            }
        }

        return true;
    }

    private static IMethodSymbol? TryFindPositionalConstructor(INamedTypeSymbol entity)
    {
        IMethodSymbol[] publicCtors = entity.InstanceConstructors
            .Where(c => c.DeclaredAccessibility == Accessibility.Public && c.Parameters.Length > 0)
            .ToArray();

        if (publicCtors.Length != 1)
        {
            return null;
        }

        IMethodSymbol ctor = publicCtors[0];
        HashSet<string> memberNames = new(StringComparer.OrdinalIgnoreCase);
        for (INamedTypeSymbol? current = entity; current != null && current.SpecialType != SpecialType.System_Object; current = current.BaseType)
        {
            foreach (IPropertySymbol p in current.GetMembers().OfType<IPropertySymbol>())
            {
                if (p.DeclaredAccessibility == Accessibility.Public && !p.IsStatic && !p.IsIndexer)
                {
                    memberNames.Add(p.Name);
                }
            }

            foreach (IFieldSymbol f in current.GetMembers().OfType<IFieldSymbol>())
            {
                if (f.DeclaredAccessibility == Accessibility.Public && !f.IsStatic)
                {
                    memberNames.Add(f.Name);
                }
            }
        }

        foreach (IParameterSymbol parameter in ctor.Parameters)
        {
            if (!memberNames.Contains(parameter.Name))
            {
                return null;
            }
        }

        return ctor;
    }

    private static bool CanEmitGroupingMaterializer(GroupByKeyInvocation invocation)
    {
        ITypeSymbol keyType = invocation.KeyType;
        if (keyType.IsAnonymousType || invocation.ParameterType.IsAnonymousType)
        {
            return false;
        }

        if (keyType is INamedTypeSymbol named && named.IsGenericType && named.ConstructedFrom.SpecialType == SpecialType.System_Nullable_T)
        {
            return false;
        }

        return IsReachableFromGeneratedCode(keyType) && IsReachableFromGeneratedCode(invocation.ParameterType);
    }

    private static bool IsReachableFromGeneratedCode(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol named && named.IsGenericType && named.ConstructedFrom.SpecialType == SpecialType.System_Nullable_T)
        {
            type = named.TypeArguments[0];
        }

        if (type is IArrayTypeSymbol array)
        {
            return IsReachableFromGeneratedCode(array.ElementType);
        }

        if (type.TypeKind is TypeKind.TypeParameter or TypeKind.Dynamic or TypeKind.Error)
        {
            return false;
        }

        for (ITypeSymbol? current = type; current != null; current = current.ContainingType)
        {
            if (current is INamedTypeSymbol namedCurrent && namedCurrent.IsFileLocal)
            {
                return false;
            }

            switch (current.DeclaredAccessibility)
            {
                case Accessibility.Public:
                case Accessibility.Internal:
                case Accessibility.ProtectedOrInternal:
                case Accessibility.NotApplicable:
                    continue;
                default:
                    return false;
            }
        }

        return true;
    }

    private static bool IsNestedCompositeShape(ITypeSymbol type)
    {
        type = StripNullableSymbol(type);

        if (IsSupportedPropertyType(type))
        {
            return false;
        }

        if (type.TypeKind != TypeKind.Class && type.TypeKind != TypeKind.Struct)
        {
            return false;
        }

        if (type.IsAbstract || type.SpecialType != SpecialType.None)
        {
            return false;
        }

        string fullName = type.ToDisplayString();
        if (fullName.StartsWith("System.") || fullName.StartsWith("Microsoft."))
        {
            return false;
        }

        return IsReachableFromGeneratedCode(type);
    }

    private static bool CanEmitNestedMaterialization(INamedTypeSymbol type, HashSet<INamedTypeSymbol> visited)
    {
        if (!visited.Add(type))
        {
            return false;
        }

        bool anyWritable = false;
        foreach (IPropertySymbol prop in EnumerateInstanceProperties(type))
        {
            if (prop.DeclaredAccessibility != Accessibility.Public || prop.SetMethod == null)
            {
                continue;
            }

            anyWritable = true;
            ITypeSymbol propType = StripNullableSymbol(prop.Type);

            if (IsSupportedPropertyType(propType))
            {
                continue;
            }

            if (propType is INamedTypeSymbol nestedNamed
                && IsNestedCompositeShape(nestedNamed)
                && CanEmitNestedMaterialization(nestedNamed, visited))
            {
                continue;
            }

            visited.Remove(type);
            return false;
        }

        visited.Remove(type);
        return anyWritable;
    }

    private static bool ShouldRecurseInto(ITypeSymbol propType)
    {
        if (StripNullableSymbol(propType) is not INamedTypeSymbol nested)
        {
            return false;
        }

        return IsNestedCompositeShape(nested)
            && CanEmitNestedMaterialization(nested, new HashSet<INamedTypeSymbol>(SymbolEqualityComparer.Default));
    }

    private static bool IsCompositeUserType(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol nt && nt.IsGenericType && nt.ConstructedFrom.SpecialType == SpecialType.System_Nullable_T)
        {
            type = nt.TypeArguments[0];
        }

        if (IsSupportedPropertyType(type))
        {
            return false;
        }

        if (type.TypeKind == TypeKind.Class && type.SpecialType == SpecialType.None && type.ContainingNamespace?.Name != "System")
        {
            string fullName = type.ToDisplayString();
            if (!fullName.StartsWith("System.") && !fullName.StartsWith("Microsoft."))
            {
                return true;
            }
        }

        return false;
    }

    private static bool IsEmittablePropertyType(ITypeSymbol type)
    {
        if (IsSupportedPropertyType(type))
        {
            return true;
        }

        if (type is INamedTypeSymbol nullable && nullable.IsGenericType && nullable.ConstructedFrom.SpecialType == SpecialType.System_Nullable_T)
        {
            type = nullable.TypeArguments[0];
        }

        return type.TypeKind != TypeKind.Interface && !type.IsAbstract;
    }

    private static bool IsSupportedPropertyType(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol named && named.IsGenericType && named.ConstructedFrom.SpecialType == SpecialType.System_Nullable_T)
        {
            type = named.TypeArguments[0];
        }

        if (type is IArrayTypeSymbol arr && arr.ElementType.SpecialType == SpecialType.System_Byte)
        {
            return true;
        }

        switch (type.SpecialType)
        {
            case SpecialType.System_Boolean:
            case SpecialType.System_Byte:
            case SpecialType.System_SByte:
            case SpecialType.System_Int16:
            case SpecialType.System_UInt16:
            case SpecialType.System_Int32:
            case SpecialType.System_UInt32:
            case SpecialType.System_Int64:
            case SpecialType.System_UInt64:
            case SpecialType.System_Single:
            case SpecialType.System_Double:
            case SpecialType.System_Decimal:
            case SpecialType.System_Char:
            case SpecialType.System_String:
            case SpecialType.System_DateTime:
                return true;
        }

        if (type.TypeKind == TypeKind.Enum)
        {
            return true;
        }

        string fullName = type.ToDisplayString();
        return fullName is "System.DateTimeOffset"
            or "System.TimeSpan"
            or "System.DateOnly"
            or "System.TimeOnly"
            or "System.Guid"
            or "byte[]";
    }

    private static void EmitMaterializer(StringBuilder sb, INamedTypeSymbol entity, string methodName, HashSet<INamedTypeSymbol> entitySet, HashSet<(INamedTypeSymbol, string)> nestedInitSet)
    {
        StringBuilder preamble = new();
        StringBuilder rowBody = new();

        int counter = 0;
        EmitEntityProperties(rowBody, preamble, "            ", entity, string.Empty, "                ", ref counter, out string resultLocalName, entitySet, nestedInitSet);

        sb.Append("        private static global::System.Func<SQLite.Framework.Models.SQLiteQueryContext, object?> ").Append(methodName).AppendLine("(SQLite.Framework.Models.SQLiteQueryContext ctx)");
        sb.AppendLine("        {");
        sb.AppendLine("            var columns = ctx.Columns!;");
        sb.Append(preamble);
        sb.AppendLine("            return rowCtx =>");
        sb.AppendLine("            {");
        sb.AppendLine("                var reader = rowCtx.Reader!;");
        sb.Append(rowBody);
        sb.Append("                return ").Append(resultLocalName).AppendLine(";");
        sb.AppendLine("            };");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void EmitEntityProperties(StringBuilder sb, StringBuilder preamble, string preambleIndent, INamedTypeSymbol entity, string columnPrefix, string indent, ref int counter, out string resultLocalName, HashSet<INamedTypeSymbol> entitySet, HashSet<(INamedTypeSymbol, string)> nestedInitSet)
    {
        bool isAnonymous = entity.IsAnonymousType;

        List<IPropertySymbol> writableProps = new();
        foreach (IPropertySymbol prop in EnumerateInstanceProperties(entity))
        {
            if (prop.DeclaredAccessibility != Accessibility.Public)
            {
                continue;
            }

            if (isAnonymous || prop.SetMethod != null)
            {
                writableProps.Add(prop);
            }
        }

        List<string> propValueLocals = new();
        List<string> nonNullChecks = new();
        foreach (IPropertySymbol prop in writableProps)
        {
            string propColumn = columnPrefix + prop.Name;
            string localSuffix = counter.ToString();
            counter++;
            string valueLocal = "__val_" + localSuffix;

            INamedTypeSymbol? nestedStripped = StripNullableSymbol(prop.Type) as INamedTypeSymbol;
            bool shouldRecurse = nestedStripped != null && ShouldRecurseInto(prop.Type);

            if (shouldRecurse && nestedStripped != null)
            {
                EmitCompositePropertyReadLocal(sb, preamble, preambleIndent, prop.Type, nestedStripped, propColumn, valueLocal, localSuffix, indent, ref counter, entitySet, nestedInitSet);
                if (nestedStripped.IsReferenceType)
                {
                    nonNullChecks.Add("(" + valueLocal + " != null)");
                }
            }
            else
            {
                EmitSimpleColumnReadLocal(sb, preamble, preambleIndent, prop.Type, propColumn, valueLocal, localSuffix, indent);
                nonNullChecks.Add("(__idx_" + localSuffix + " >= 0 && !reader.IsDBNull(__idx_" + localSuffix + "))");
            }

            propValueLocals.Add(valueLocal);
        }

        string resultSuffix = counter.ToString();
        counter++;
        resultLocalName = "__entity_" + resultSuffix;

        if (isAnonymous)
        {
            sb.Append(indent).Append("var ").Append(resultLocalName).AppendLine(" = new");
            sb.Append(indent).AppendLine("{");
            for (int i = 0; i < writableProps.Count; i++)
            {
                sb.Append(indent).Append("    ").Append(writableProps[i].Name).Append(" = ").Append(propValueLocals[i]);
                sb.AppendLine(i == writableProps.Count - 1 ? "" : ",");
            }
            sb.Append(indent).AppendLine("};");
            return;
        }

        string typeName = entity.ToDisplayString();
        List<IPropertySymbol> requiredNotMapped = GetRequiredNotMappedProperties(entity);

        IMethodSymbol? positionalCtor = HasPublicParameterlessConstructor(entity) ? null : TryFindPositionalConstructor(entity);
        List<int> inaccessibleIndexes = new();

        if (positionalCtor != null)
        {
            HashSet<string> ctorParameterNames = new(StringComparer.OrdinalIgnoreCase);
            foreach (IParameterSymbol parameter in positionalCtor.Parameters)
            {
                ctorParameterNames.Add(parameter.Name);
            }

            sb.Append(indent).Append(typeName).Append(" ").Append(resultLocalName).Append(" = new ").Append(FormatNewType(entity)).Append("(");
            for (int pi = 0; pi < positionalCtor.Parameters.Length; pi++)
            {
                if (pi > 0)
                {
                    sb.Append(", ");
                }

                int sourceIndex = writableProps.FindIndex(p => string.Equals(p.Name, positionalCtor.Parameters[pi].Name, StringComparison.OrdinalIgnoreCase));
                sb.Append(sourceIndex >= 0 ? propValueLocals[sourceIndex] : "default");
            }

            sb.Append(")");

            List<int> extraIndexes = new();
            for (int i = 0; i < writableProps.Count; i++)
            {
                if (ctorParameterNames.Contains(writableProps[i].Name))
                {
                    continue;
                }

                if (IsSetterAccessibleFromGeneratedCode(writableProps[i]))
                {
                    extraIndexes.Add(i);
                }
                else
                {
                    inaccessibleIndexes.Add(i);
                }
            }

            if (extraIndexes.Count > 0 || requiredNotMapped.Count > 0)
            {
                sb.Append(" { ");
                bool first = true;
                foreach (int ei in extraIndexes)
                {
                    if (!first)
                    {
                        sb.Append(", ");
                    }
                    first = false;
                    sb.Append(writableProps[ei].Name).Append(" = ").Append(propValueLocals[ei]);
                }
                foreach (IPropertySymbol prop in requiredNotMapped)
                {
                    if (!first)
                    {
                        sb.Append(", ");
                    }
                    first = false;
                    sb.Append(prop.Name).Append(" = default!");
                }
                sb.Append(" }");
            }

            sb.AppendLine(";");
        }
        else
        {
            List<int> initializerIndexes = new();
            for (int i = 0; i < writableProps.Count; i++)
            {
                if (IsSetterAccessibleFromGeneratedCode(writableProps[i]))
                {
                    initializerIndexes.Add(i);
                }
                else
                {
                    inaccessibleIndexes.Add(i);
                }
            }

            int totalEntries = initializerIndexes.Count + requiredNotMapped.Count;

            sb.Append(indent).Append(typeName).Append(" ").Append(resultLocalName).AppendLine(" = new()");
            sb.Append(indent).AppendLine("{");

            int written = 0;
            foreach (int i in initializerIndexes)
            {
                sb.Append(indent).Append("    ").Append(writableProps[i].Name).Append(" = ").Append(propValueLocals[i]);
                written++;
                sb.AppendLine(written == totalEntries ? "" : ",");
            }

            foreach (IPropertySymbol prop in requiredNotMapped)
            {
                sb.Append(indent).Append("    ").Append(prop.Name).Append(" = default!");
                written++;
                sb.AppendLine(written == totalEntries ? "" : ",");
            }

            sb.Append(indent).AppendLine("};");
        }

        EmitInaccessibleSetterAssignments(sb, preamble, preambleIndent, indent, entity, typeName, resultLocalName, resultSuffix, writableProps, propValueLocals, inaccessibleIndexes);

        if (columnPrefix.Length > 0 && entity.IsReferenceType && nonNullChecks.Count > 0)
        {
            sb.Append(indent).Append("if (!(").Append(string.Join(" || ", nonNullChecks)).Append(")) ").Append(resultLocalName).AppendLine(" = null;");
        }
    }

    private static void EmitInaccessibleSetterAssignments(StringBuilder sb, StringBuilder preamble, string preambleIndent, string indent, INamedTypeSymbol entity, string typeName, string resultLocalName, string resultSuffix, List<IPropertySymbol> writableProps, List<string> propValueLocals, List<int> indexes)
    {
        if (indexes.Count == 0)
        {
            return;
        }

        foreach (int i in indexes)
        {
            preamble.Append(preambleIndent).Append("global::System.Reflection.PropertyInfo __pset_").Append(resultSuffix).Append('_').Append(i)
                .Append(" = typeof(").Append(typeName).Append(").GetProperty(\"").Append(writableProps[i].Name)
                .AppendLine("\", global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic)!;");
        }

        if (entity.IsValueType)
        {
            string boxLocal = "__box_" + resultSuffix;
            sb.Append(indent).Append("object ").Append(boxLocal).Append(" = ").Append(resultLocalName).AppendLine(";");
            foreach (int i in indexes)
            {
                sb.Append(indent).Append("__pset_").Append(resultSuffix).Append('_').Append(i).Append(".SetValue(").Append(boxLocal).Append(", ").Append(propValueLocals[i]).AppendLine(");");
            }
            sb.Append(indent).Append(resultLocalName).Append(" = (").Append(typeName).Append(')').Append(boxLocal).AppendLine(";");
        }
        else
        {
            foreach (int i in indexes)
            {
                sb.Append(indent).Append("__pset_").Append(resultSuffix).Append('_').Append(i).Append(".SetValue(").Append(resultLocalName).Append(", ").Append(propValueLocals[i]).AppendLine(");");
            }
        }
    }

    private static List<IPropertySymbol> GetRequiredNotMappedProperties(INamedTypeSymbol entity)
    {
        List<IPropertySymbol> result = new();
        HashSet<string> seen = new(StringComparer.Ordinal);
        for (INamedTypeSymbol? current = entity; current != null && current.SpecialType != SpecialType.System_Object; current = current.BaseType)
        {
            foreach (ISymbol member in current.GetMembers())
            {
                if (member is not IPropertySymbol prop || prop.IsStatic || prop.IsIndexer)
                {
                    continue;
                }

                if (!prop.IsRequired || !HasNotMappedAttribute(prop))
                {
                    continue;
                }

                if (prop.SetMethod == null || prop.DeclaredAccessibility != Accessibility.Public)
                {
                    continue;
                }

                if (!seen.Add(prop.Name))
                {
                    continue;
                }

                result.Add(prop);
            }
        }
        return result;
    }

    private static void EmitSimpleColumnReadLocal(StringBuilder sb, StringBuilder preamble, string preambleIndent, ITypeSymbol propType, string columnName, string valueLocal, string localSuffix, string indent, bool caseInsensitive = false)
    {
        _ = caseInsensitive;
        string propTypeDisplay = propType.ToDisplayString();
        string strippedDisplay = StripNullable(propTypeDisplay);
        string convReadDisplay = SelectMaterializerEmitter.IsNullableValueType(propType) ? propTypeDisplay : strippedDisplay;
        string safeColumn = columnName.Replace("\"", "\\\"");
        string idxLocal = "__idx_" + localSuffix;
        bool isEnum = StripNullableSymbol(propType).TypeKind == TypeKind.Enum;

        preamble.Append(preambleIndent).Append("int ").Append(idxLocal)
            .Append(" = FindColumnIndex(columns, \"").Append(safeColumn).AppendLine("\");");

        sb.Append(indent).Append(propTypeDisplay).Append(" ").Append(valueLocal).Append(" = default");
        if (propType.IsReferenceType || propType.NullableAnnotation == NullableAnnotation.Annotated)
        {
            sb.Append("!");
        }
        sb.AppendLine(";");
        sb.Append(indent).Append("if (").Append(idxLocal).AppendLine(" >= 0)");
        sb.Append(indent).AppendLine("{");

        bool isNullable = propType.NullableAnnotation == NullableAnnotation.Annotated || propType.IsReferenceType
            || (propType is INamedTypeSymbol nt && nt.IsGenericType && nt.ConstructedFrom.SpecialType == SpecialType.System_Nullable_T);

        if (!isEnum && SelectMaterializerEmitter.TryGetFastPathAccessor(propType, out string? accessor, out bool handlesNull))
        {
            sb.Append(indent).Append("    if (reader.HasConverter(typeof(").Append(strippedDisplay).AppendLine(")))");
            sb.Append(indent).AppendLine("    {");
            sb.Append(indent).Append("        object? __raw_").Append(localSuffix).Append(" = reader.GetValue(").Append(idxLocal).Append(", reader.GetColumnType(").Append(idxLocal).Append("), typeof(").Append(convReadDisplay).AppendLine("));");
            sb.Append(indent).Append("        if (__raw_").Append(localSuffix).Append(" != null) ").Append(valueLocal).Append(" = (").Append(propTypeDisplay).Append(")__raw_").Append(localSuffix).AppendLine("!;");
            sb.Append(indent).AppendLine("    }");
            sb.Append(indent).AppendLine("    else");
            sb.Append(indent).AppendLine("    {");
            if (isNullable && !handlesNull)
            {
                sb.Append(indent).Append("        if (!reader.IsDBNull(").Append(idxLocal).AppendLine("))");
                sb.Append(indent).Append("        ").Append(valueLocal).Append(" = ").Append("reader.").Append(accessor).Append("(").Append(idxLocal).AppendLine(");");
            }
            else
            {
                sb.Append(indent).Append("        ").Append(valueLocal).Append(" = ").Append("reader.").Append(accessor).Append("(").Append(idxLocal).AppendLine(");");
            }
            sb.Append(indent).AppendLine("    }");
            sb.Append(indent).AppendLine("}");
            return;
        }

        sb.Append(indent).Append("    object? __raw_").Append(localSuffix).Append(" = reader.GetValue(").Append(idxLocal).Append(", reader.GetColumnType(").Append(idxLocal).Append("), typeof(").Append(convReadDisplay).AppendLine("));");
        sb.Append(indent).Append("    if (__raw_").Append(localSuffix).AppendLine(" != null)");
        sb.Append(indent).AppendLine("    {");
        sb.Append(indent).Append("        ").Append(valueLocal).Append(" = (").Append(propTypeDisplay).Append(")__raw_").Append(localSuffix).AppendLine("!;");
        sb.Append(indent).AppendLine("    }");
        sb.Append(indent).AppendLine("}");
    }

    private static void EmitCompositePropertyReadLocal(StringBuilder sb, StringBuilder preamble, string preambleIndent, ITypeSymbol propType, INamedTypeSymbol nestedType, string columnName, string valueLocal, string localSuffix, string indent, ref int counter, HashSet<INamedTypeSymbol> entitySet, HashSet<(INamedTypeSymbol, string)> nestedInitSet)
    {
        string safeColumn = columnName.Replace("\"", "\\\"");
        string flatIdx = "__cidx_" + localSuffix;

        preamble.Append(preambleIndent).Append("int ").Append(flatIdx)
            .Append(" = FindColumnIndex(columns, \"").Append(safeColumn).AppendLine("\");");

        EmitEntityProperties(sb, preamble, preambleIndent, nestedType, columnName + ".", indent, ref counter, out string nestedResult, entitySet, nestedInitSet);

        string propTypeDisplay = propType.ToDisplayString();
        string strippedDisplay = nestedType.ToDisplayString();

        sb.Append(indent).Append(propTypeDisplay).Append(" ").Append(valueLocal).AppendLine(";");
        sb.Append(indent).Append("if (").Append(flatIdx).AppendLine(" >= 0)");
        sb.Append(indent).AppendLine("{");
        sb.Append(indent).Append("    object? __craw_").Append(localSuffix).Append(" = reader.GetValue(").Append(flatIdx).Append(", reader.GetColumnType(").Append(flatIdx).Append("), typeof(").Append(strippedDisplay).AppendLine("));");
        sb.Append(indent).Append("    ").Append(valueLocal).Append(" = __craw_").Append(localSuffix).Append(" != null ? (").Append(propTypeDisplay).Append(")__craw_").Append(localSuffix).Append(" : ").Append(nestedResult).AppendLine(";");
        sb.Append(indent).AppendLine("}");
        sb.Append(indent).AppendLine("else");
        sb.Append(indent).AppendLine("{");
        sb.Append(indent).Append("    ").Append(valueLocal).Append(" = ").Append(nestedResult).AppendLine(";");
        sb.Append(indent).AppendLine("}");
    }

    private static string FormatNewType(INamedTypeSymbol entity)
    {
        if (!entity.IsTupleType)
        {
            return entity.ToDisplayString();
        }

        INamedTypeSymbol underlying = entity.TupleUnderlyingType ?? entity;
        StringBuilder sb = new();
        sb.Append("global::System.ValueTuple<");
        for (int i = 0; i < underlying.TypeArguments.Length; i++)
        {
            if (i > 0)
            {
                sb.Append(", ");
            }

            sb.Append(underlying.TypeArguments[i].ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat));
        }

        sb.Append('>');
        return sb.ToString();
    }

    private static void EmitPositionalMaterializer(StringBuilder sb, INamedTypeSymbol entity, string methodName)
    {
        IMethodSymbol ctor = TryFindPositionalConstructor(entity)!;
        string typeName = FormatNewType(entity);

        HashSet<string> ctorParameterNames = new(StringComparer.OrdinalIgnoreCase);
        foreach (IParameterSymbol parameter in ctor.Parameters)
        {
            ctorParameterNames.Add(parameter.Name);
        }

        StringBuilder preamble = new();
        StringBuilder rowBody = new();

        int counter = 0;
        List<string> argLocals = new();
        foreach (IParameterSymbol parameter in ctor.Parameters)
        {
            string suffix = counter.ToString();
            counter++;
            string argLocal = "__arg_" + suffix;
            argLocals.Add(argLocal);
            EmitSimpleColumnReadLocal(rowBody, preamble, "            ", parameter.Type, parameter.Name, argLocal, suffix, "                ", caseInsensitive: true);
        }

        List<(string Property, string Local)> extras = new();
        foreach (IPropertySymbol prop in EnumerateInstanceProperties(entity))
        {
            if (prop.DeclaredAccessibility != Accessibility.Public || prop.SetMethod == null || ctorParameterNames.Contains(prop.Name))
            {
                continue;
            }

            string suffix = counter.ToString();
            counter++;
            string valueLocal = "__ext_" + suffix;
            EmitSimpleColumnReadLocal(rowBody, preamble, "            ", prop.Type, prop.Name, valueLocal, suffix, "                ", caseInsensitive: true);
            extras.Add((prop.Name, valueLocal));
        }

        sb.Append("        private static global::System.Func<SQLite.Framework.Models.SQLiteQueryContext, object?> ").Append(methodName).AppendLine("(SQLite.Framework.Models.SQLiteQueryContext ctx)");
        sb.AppendLine("        {");
        sb.AppendLine("            var columns = ctx.Columns!;");
        sb.Append(preamble);
        sb.AppendLine("            return rowCtx =>");
        sb.AppendLine("            {");
        sb.AppendLine("                var reader = rowCtx.Reader!;");
        sb.Append(rowBody);
        sb.Append("                return new ").Append(typeName).Append("(");
        for (int i = 0; i < argLocals.Count; i++)
        {
            if (i > 0) sb.Append(", ");
            sb.Append(argLocals[i]);
        }
        sb.Append(")");
        if (extras.Count > 0)
        {
            sb.Append(" { ");
            for (int i = 0; i < extras.Count; i++)
            {
                if (i > 0) sb.Append(", ");
                sb.Append(extras[i].Property).Append(" = ").Append(extras[i].Local);
            }
            sb.Append(" }");
        }
        sb.AppendLine(";");
        sb.AppendLine("            };");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void EmitPositionalReflectionMaterializer(StringBuilder sb, INamedTypeSymbol entity, string methodName)
    {
        IMethodSymbol ctor = TryFindPositionalConstructor(entity)!;
        string typeField = $"s_type_{methodName}";
        string ctorField = $"s_ctor_{methodName}";
        string qualifiedName = GetMetadataFullName(entity) + ", " + (entity.ContainingAssembly?.Name ?? string.Empty);

        sb.Append("        private static readonly global::System.Type ").Append(typeField)
            .Append(" = global::System.Type.GetType(").Append(EscapeStringLiteral(qualifiedName)).AppendLine(", throwOnError: true)!;");
        sb.Append("        private static readonly global::System.Reflection.ConstructorInfo ").Append(ctorField)
            .Append(" = global::System.Array.Find(").Append(typeField).Append(".GetConstructors(), c => c.GetParameters().Length == ").Append(ctor.Parameters.Length).AppendLine(")!;");

        HashSet<string> ctorParameterNames = new(StringComparer.OrdinalIgnoreCase);
        foreach (IParameterSymbol parameter in ctor.Parameters)
        {
            ctorParameterNames.Add(parameter.Name);
        }

        List<IPropertySymbol> extras = new();
        foreach (IPropertySymbol prop in EnumerateInstanceProperties(entity))
        {
            if (prop.DeclaredAccessibility != Accessibility.Public || prop.SetMethod == null || ctorParameterNames.Contains(prop.Name))
            {
                continue;
            }

            extras.Add(prop);
        }

        foreach (IPropertySymbol prop in extras)
        {
            sb.Append("        private static readonly global::System.Reflection.PropertyInfo s_prop_").Append(methodName).Append("_").Append(prop.Name)
                .Append(" = ").Append(typeField).Append(".GetProperty(\"").Append(prop.Name).AppendLine("\", global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic)!;");
        }

        sb.AppendLine();

        StringBuilder preamble = new();
        StringBuilder rowBody = new();
        int counter = 0;
        List<string> argLocals = new();
        foreach (IParameterSymbol parameter in ctor.Parameters)
        {
            string suffix = counter.ToString();
            counter++;
            string argLocal = "__arg_" + suffix;
            argLocals.Add(argLocal);
            EmitReflectionConvertedRead(rowBody, preamble, parameter.Type, parameter.Name, argLocal, suffix);
        }

        List<(string Property, string Local)> extraReads = new();
        foreach (IPropertySymbol prop in extras)
        {
            string suffix = counter.ToString();
            counter++;
            string valueLocal = "__ext_" + suffix;
            EmitReflectionConvertedRead(rowBody, preamble, prop.Type, prop.Name, valueLocal, suffix);
            extraReads.Add((prop.Name, valueLocal));
        }

        sb.Append("        private static global::System.Func<SQLite.Framework.Models.SQLiteQueryContext, object?> ").Append(methodName).AppendLine("(SQLite.Framework.Models.SQLiteQueryContext ctx)");
        sb.AppendLine("        {");
        sb.AppendLine("            var columns = ctx.Columns!;");
        sb.Append(preamble);
        sb.AppendLine("            return rowCtx =>");
        sb.AppendLine("            {");
        sb.AppendLine("                var reader = rowCtx.Reader!;");
        sb.Append(rowBody);
        sb.Append("                object?[] __args = new object?[] { ");
        for (int i = 0; i < argLocals.Count; i++)
        {
            if (i > 0) sb.Append(", ");
            sb.Append(argLocals[i]);
        }
        sb.AppendLine(" };");
        sb.Append("                object __instance = ").Append(ctorField).AppendLine(".Invoke(__args)!;");
        foreach ((string property, string local) in extraReads)
        {
            sb.Append("                if (").Append(local).AppendLine(" != null)");
            sb.AppendLine("                {");
            sb.Append("                    s_prop_").Append(methodName).Append("_").Append(property).Append(".SetValue(__instance, ").Append(local).AppendLine(");");
            sb.AppendLine("                }");
        }
        sb.AppendLine("                return __instance;");
        sb.AppendLine("            };");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void EmitReflectionConvertedRead(StringBuilder body, StringBuilder preamble, ITypeSymbol type, string columnName, string valueLocal, string suffix)
    {
        ITypeSymbol stripped = StripNullableSymbol(type);
        string strippedDisplay = stripped.ToDisplayString();
        string convReadDisplay = SelectMaterializerEmitter.IsNullableValueType(type) ? type.ToDisplayString() : strippedDisplay;
        string safeColumn = columnName.Replace("\"", "\\\"");
        string idxLocal = "__ridx_" + suffix;

        preamble.Append("            int ").Append(idxLocal)
            .Append(" = FindColumnIndex(columns, \"").Append(safeColumn).AppendLine("\");");

        body.Append("                object? ").Append(valueLocal).AppendLine(" = null;");
        body.Append("                if (").Append(idxLocal).AppendLine(" >= 0)");
        body.AppendLine("                {");
        body.Append("                    object? __raw_").Append(suffix).Append(" = reader.GetValue(").Append(idxLocal).Append(", reader.GetColumnType(").Append(idxLocal).Append("), typeof(").Append(convReadDisplay).AppendLine("));");
        body.Append("                    if (__raw_").Append(suffix).AppendLine(" != null)");
        body.AppendLine("                    {");
        body.Append("                        ").Append(valueLocal).Append(" = __raw_").Append(suffix).AppendLine(";");
        body.AppendLine("                    }");
        body.AppendLine("                }");
    }

    private static void EmitReflectionMaterializer(StringBuilder sb, INamedTypeSymbol entity, string methodName, HashSet<INamedTypeSymbol> entitySet, HashSet<(INamedTypeSymbol, string)> nestedInitSet)
    {
        string typeField = $"s_type_{methodName}";
        string metadataName = GetMetadataFullName(entity);
        string assemblyName = entity.ContainingAssembly?.Name ?? string.Empty;
        string qualifiedName = metadataName + ", " + assemblyName;

        sb.Append("        private static readonly global::System.Type ").Append(typeField)
            .Append(" = global::System.Type.GetType(").Append(EscapeStringLiteral(qualifiedName))
            .AppendLine(", throwOnError: true)!;");

        List<IPropertySymbol> writableProps = new();
        foreach (IPropertySymbol prop in EnumerateInstanceProperties(entity))
        {
            if (prop.SetMethod != null)
            {
                writableProps.Add(prop);
            }
        }

        foreach (IPropertySymbol prop in writableProps)
        {
            sb.Append("        private static readonly global::System.Reflection.PropertyInfo s_prop_").Append(methodName).Append("_").Append(prop.Name)
                .Append(" = ").Append(typeField)
                .Append(".GetProperty(\"").Append(prop.Name).AppendLine("\", global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic)!;");

            ITypeSymbol propStripped = StripNullableSymbol(prop.Type);
            if (!IsReachableFromGeneratedCode(propStripped))
            {
                string propTypeField = $"s_propType_{methodName}_{prop.Name}";
                string propMetadata = propStripped is INamedTypeSymbol named
                    ? GetMetadataFullName(named) + ", " + (named.ContainingAssembly?.Name ?? string.Empty)
                    : propStripped.ToDisplayString();
                string strippedTypeExpr = "global::System.Type.GetType(" + EscapeStringLiteral(propMetadata) + ", throwOnError: true)!";
                string fieldTypeExpr = SelectMaterializerEmitter.IsNullableValueType(prop.Type)
                    ? "typeof(global::System.Nullable<>).MakeGenericType(" + strippedTypeExpr + ")"
                    : strippedTypeExpr;
                sb.Append("        private static readonly global::System.Type ").Append(propTypeField)
                    .Append(" = ").Append(fieldTypeExpr).AppendLine(";");
            }
        }

        sb.AppendLine();

        StringBuilder preamble = new();
        StringBuilder rowBody = new();

        int counter = 0;
        foreach (IPropertySymbol prop in writableProps)
        {
            string propName = prop.Name;
            ITypeSymbol propStripped = StripNullableSymbol(prop.Type);
            INamedTypeSymbol? nestedStripped = propStripped as INamedTypeSymbol;
            bool shouldRecurse = nestedStripped != null
                && nestedStripped.TypeKind == TypeKind.Class
                && IsReachableFromGeneratedCode(propStripped)
                && entitySet.Contains(nestedStripped)
                && nestedInitSet.Contains((entity, prop.Name));

            if (shouldRecurse && nestedStripped != null)
            {
                EmitEntityProperties(rowBody, preamble, "            ", nestedStripped, propName + ".", "                ", ref counter, out string nestedResult, entitySet, nestedInitSet);
                rowBody.Append("                s_prop_").Append(methodName).Append("_").Append(propName).Append(".SetValue(result, ").Append(nestedResult).AppendLine(");");
                continue;
            }

            string typeExpression;
            if (IsReachableFromGeneratedCode(propStripped))
            {
                typeExpression = SelectMaterializerEmitter.IsNullableValueType(prop.Type)
                    ? "typeof(" + prop.Type.ToDisplayString() + ")"
                    : "typeof(" + propStripped.ToDisplayString() + ")";
            }
            else
            {
                typeExpression = $"s_propType_{methodName}_{propName}";
            }

            preamble.Append("            int idx_").Append(propName)
                .Append(" = FindColumnIndex(columns, \"").Append(propName).AppendLine("\");");

            rowBody.Append("                if (idx_").Append(propName).AppendLine(" >= 0)");
            rowBody.AppendLine("                {");
            rowBody.Append("                    object? value_").Append(propName).Append(" = reader.GetValue(idx_").Append(propName).Append(", reader.GetColumnType(idx_").Append(propName).Append("), ").Append(typeExpression).AppendLine(");");
            rowBody.Append("                    if (value_").Append(propName).AppendLine(" != null)");
            rowBody.AppendLine("                    {");
            rowBody.Append("                        s_prop_").Append(methodName).Append("_").Append(propName).Append(".SetValue(result, value_").Append(propName).AppendLine(");");
            rowBody.AppendLine("                    }");
            rowBody.AppendLine("                }");
        }

        sb.Append("        private static global::System.Func<SQLite.Framework.Models.SQLiteQueryContext, object?> ").Append(methodName).AppendLine("(SQLite.Framework.Models.SQLiteQueryContext ctx)");
        sb.AppendLine("        {");
        sb.AppendLine("            var columns = ctx.Columns!;");
        sb.Append(preamble);
        sb.AppendLine("            return rowCtx =>");
        sb.AppendLine("            {");
        sb.AppendLine("                var reader = rowCtx.Reader!;");
        sb.Append("                object result = global::System.Activator.CreateInstance(").Append(typeField).AppendLine(", nonPublic: true)!;");
        sb.Append(rowBody);
        sb.AppendLine("                return result;");
        sb.AppendLine("            };");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void EmitAnonymousMaterializer(StringBuilder sb, INamedTypeSymbol entity, string methodName, HashSet<INamedTypeSymbol> entitySet, HashSet<(INamedTypeSymbol, string)> nestedInitSet)
    {
        List<IPropertySymbol> props = entity.GetMembers().OfType<IPropertySymbol>().ToList();
        EmitAnonymousMaterializerDirect(sb, entity, methodName, props, entitySet, nestedInitSet);
    }

    private static void EmitAnonymousMaterializerDirect(StringBuilder sb, INamedTypeSymbol entity, string methodName, List<IPropertySymbol> props, HashSet<INamedTypeSymbol> entitySet, HashSet<(INamedTypeSymbol, string)> nestedInitSet)
    {
        string typeField = $"s_type_{methodName}";

        StringBuilder sample = new();
        sample.Append("new { ");
        for (int i = 0; i < props.Count; i++)
        {
            if (i > 0)
            {
                sample.Append(", ");
            }
            sample.Append(props[i].Name).Append(" = ").Append(BuildSampleExpression(props[i].Type));
        }
        sample.Append(" }");

        sb.Append("        private static readonly global::System.Type ").Append(typeField)
            .Append(" = (").Append(sample.ToString()).AppendLine(").GetType();");
        sb.AppendLine();

        StringBuilder preamble = new();
        StringBuilder rowBody = new();

        int nestedCounter = 0;
        Dictionary<string, string> nestedResultLocals = new();

        foreach (IPropertySymbol prop in props)
        {
            string propName = prop.Name;
            string propTypeDisplay = prop.Type.ToDisplayString();

            if (StripNullableSymbol(prop.Type) is INamedTypeSymbol strippedNamed
                && strippedNamed.TypeKind == TypeKind.Class
                && entitySet.Contains(strippedNamed)
                && IsCompositeUserType(strippedNamed))
            {
                EmitEntityProperties(rowBody, preamble, "            ", strippedNamed, propName + ".", "                ", ref nestedCounter, out string nestedResult, entitySet, nestedInitSet);
                nestedResultLocals[propName] = nestedResult;
                continue;
            }

            if (StripNullableSymbol(prop.Type) is INamedTypeSymbol strippedAnon && strippedAnon.IsAnonymousType)
            {
                EmitAnonymousProperties(rowBody, preamble, "            ", strippedAnon, propName + ".", "                ", ref nestedCounter, out string nestedResult);
                nestedResultLocals[propName] = nestedResult;
                continue;
            }

            string strippedDisplay = StripNullableSymbol(prop.Type).ToDisplayString();
            string convReadDisplay = SelectMaterializerEmitter.IsNullableValueType(prop.Type) ? propTypeDisplay : strippedDisplay;
            preamble.Append("            int idx_").Append(propName)
                .Append(" = FindColumnIndex(columns, \"").Append(propName).AppendLine("\");");

            rowBody.Append("                ").Append(propTypeDisplay).Append(" value_").Append(propName).Append(" = default");
            bool isAnnotatedOrRef = prop.Type.NullableAnnotation == NullableAnnotation.Annotated || prop.Type.IsReferenceType;
            if (isAnnotatedOrRef)
            {
                rowBody.Append("!");
            }
            rowBody.AppendLine(";");
            rowBody.Append("                if (idx_").Append(propName).AppendLine(" >= 0)");
            rowBody.AppendLine("                {");

            bool propIsNullable = isAnnotatedOrRef
                || (prop.Type is INamedTypeSymbol propNt && propNt.IsGenericType && propNt.ConstructedFrom.SpecialType == SpecialType.System_Nullable_T);

            if (SelectMaterializerEmitter.TryGetFastPathAccessor(prop.Type, out string? accessor, out bool handlesNull))
            {
                rowBody.Append("                    if (reader.HasConverter(typeof(").Append(strippedDisplay).AppendLine(")))");
                rowBody.AppendLine("                    {");
                rowBody.Append("                        object? raw_").Append(propName).Append(" = reader.GetValue(idx_").Append(propName).Append(", reader.GetColumnType(idx_").Append(propName).Append("), typeof(").Append(convReadDisplay).AppendLine("));");
                rowBody.Append("                        if (raw_").Append(propName).Append(" != null) value_").Append(propName).Append(" = (").Append(propTypeDisplay).Append(")raw_").Append(propName).AppendLine("!;");
                rowBody.AppendLine("                    }");
                rowBody.AppendLine("                    else");
                rowBody.AppendLine("                    {");
                if (propIsNullable && !handlesNull)
                {
                    rowBody.Append("                        if (!reader.IsDBNull(idx_").Append(propName).AppendLine("))");
                    rowBody.Append("                        value_").Append(propName).Append(" = ").Append("reader.").Append(accessor).Append("(idx_").Append(propName).AppendLine(");");
                }
                else
                {
                    rowBody.Append("                        value_").Append(propName).Append(" = ").Append("reader.").Append(accessor).Append("(idx_").Append(propName).AppendLine(");");
                }
                rowBody.AppendLine("                    }");
            }
            else
            {
                rowBody.Append("                    object? raw_").Append(propName).Append(" = reader.GetValue(idx_").Append(propName).Append(", reader.GetColumnType(idx_").Append(propName).Append("), typeof(").Append(convReadDisplay).AppendLine("));");
                rowBody.Append("                    if (raw_").Append(propName).AppendLine(" != null)");
                rowBody.AppendLine("                    {");
                rowBody.Append("                        value_").Append(propName).Append(" = (").Append(propTypeDisplay).Append(")raw_").Append(propName).AppendLine("!;");
                rowBody.AppendLine("                    }");
            }
            rowBody.AppendLine("                }");
        }

        sb.Append("        private static global::System.Func<SQLite.Framework.Models.SQLiteQueryContext, object?> ").Append(methodName).AppendLine("(SQLite.Framework.Models.SQLiteQueryContext ctx)");
        sb.AppendLine("        {");
        sb.AppendLine("            var columns = ctx.Columns!;");
        sb.Append(preamble);
        sb.AppendLine("            return rowCtx =>");
        sb.AppendLine("            {");
        sb.AppendLine("                var reader = rowCtx.Reader!;");
        sb.Append(rowBody);
        sb.Append("                return new { ");
        for (int i = 0; i < props.Count; i++)
        {
            if (i > 0)
            {
                sb.Append(", ");
            }
            string propName = props[i].Name;
            string source = nestedResultLocals.TryGetValue(propName, out string? nestedLocal)
                ? nestedLocal
                : "value_" + propName;
            sb.Append(propName).Append(" = ").Append(source);
        }
        sb.AppendLine(" };");
        sb.AppendLine("            };");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void EmitAnonymousProperties(StringBuilder sb, StringBuilder preamble, string preambleIndent, INamedTypeSymbol anonType, string columnPrefix, string indent, ref int counter, out string resultLocalName)
    {
        List<IPropertySymbol> props = anonType.GetMembers().OfType<IPropertySymbol>().ToList();
        List<string> propValueLocals = new();

        foreach (IPropertySymbol prop in props)
        {
            string propColumn = columnPrefix + prop.Name;
            string localSuffix = counter.ToString();
            counter++;
            string valueLocal = "__val_" + localSuffix;

            if (StripNullableSymbol(prop.Type) is INamedTypeSymbol nestedAnon && nestedAnon.IsAnonymousType)
            {
                EmitAnonymousProperties(sb, preamble, preambleIndent, nestedAnon, propColumn + ".", indent, ref counter, out string nestedResult);
                sb.Append(indent).Append("var ").Append(valueLocal).Append(" = ").Append(nestedResult).AppendLine(";");
            }
            else
            {
                EmitSimpleColumnReadLocal(sb, preamble, preambleIndent, prop.Type, propColumn, valueLocal, localSuffix, indent);
            }
            propValueLocals.Add(valueLocal);
        }

        string resultSuffix = counter.ToString();
        counter++;
        resultLocalName = "__anon_" + resultSuffix;

        sb.Append(indent).Append("var ").Append(resultLocalName).AppendLine(" = new");
        sb.Append(indent).AppendLine("{");
        for (int i = 0; i < props.Count; i++)
        {
            sb.Append(indent).Append("    ").Append(props[i].Name).Append(" = ").Append(propValueLocals[i]);
            sb.AppendLine(i == props.Count - 1 ? "" : ",");
        }
        sb.Append(indent).AppendLine("};");
    }

    private static string BuildSampleExpression(ITypeSymbol type)
    {
        if (StripNullableSymbol(type) is INamedTypeSymbol nested && nested.IsAnonymousType)
        {
            StringBuilder b = new();
            b.Append("new { ");
            List<IPropertySymbol> nestedProps = nested.GetMembers().OfType<IPropertySymbol>().ToList();
            for (int i = 0; i < nestedProps.Count; i++)
            {
                if (i > 0)
                {
                    b.Append(", ");
                }
                b.Append(nestedProps[i].Name).Append(" = ").Append(BuildSampleExpression(nestedProps[i].Type));
            }
            b.Append(" }");
            return b.ToString();
        }

        string display = type.ToDisplayString();
        string defaultExpr = "default(" + display + ")";
        if (type.IsReferenceType && type.NullableAnnotation != NullableAnnotation.Annotated)
        {
            defaultExpr += "!";
        }
        return defaultExpr;
    }

    private static IEnumerable<IPropertySymbol> EnumerateInstanceProperties(INamedTypeSymbol entity)
    {
        HashSet<string> seen = new(StringComparer.Ordinal);
        for (INamedTypeSymbol? current = entity; current != null && current.SpecialType != SpecialType.System_Object; current = current.BaseType)
        {
            foreach (ISymbol member in current.GetMembers())
            {
                if (member is not IPropertySymbol prop || prop.IsStatic || prop.IsIndexer)
                {
                    continue;
                }

                if (HasNotMappedAttribute(prop))
                {
                    continue;
                }

                if (!seen.Add(prop.Name))
                {
                    continue;
                }

                yield return prop;
            }
        }
    }

    private static bool HasNotMappedAttribute(IPropertySymbol prop)
    {
        foreach (AttributeData attr in prop.GetAttributes())
        {
            if (attr.AttributeClass is { Name: "NotMappedAttribute" } cls
                && cls.ContainingNamespace?.ToDisplayString() == "System.ComponentModel.DataAnnotations.Schema")
            {
                return true;
            }
        }
        return false;
    }

    private static ITypeSymbol StripNullableSymbol(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol nt && nt.IsGenericType && nt.ConstructedFrom.SpecialType == SpecialType.System_Nullable_T)
        {
            return nt.TypeArguments[0];
        }
        if (type.NullableAnnotation == NullableAnnotation.Annotated && type.IsReferenceType)
        {
            return type.WithNullableAnnotation(NullableAnnotation.NotAnnotated);
        }
        return type;
    }

    private static string GetMetadataFullName(INamedTypeSymbol symbol)
    {
        StringBuilder sb = new();
        AppendMetadataName(sb, symbol);
        return sb.ToString();
    }

    private static void AppendMetadataName(StringBuilder sb, INamedTypeSymbol symbol)
    {
        if (symbol.ContainingType != null)
        {
            AppendMetadataName(sb, symbol.ContainingType);
            sb.Append('+');
        }
        else
        {
            INamespaceSymbol? ns = symbol.ContainingNamespace;
            if (ns is { IsGlobalNamespace: false })
            {
                sb.Append(ns.ToDisplayString()).Append('.');
            }
        }
        sb.Append(symbol.MetadataName);
    }

    private static string StripNullable(string displayType)
    {
        if (displayType.EndsWith("?"))
        {
            return displayType.Substring(0, displayType.Length - 1);
        }
        return displayType;
    }

    private static string SanitizeIdentifier(string name)
    {
        StringBuilder sb = new(name.Length);
        foreach (char c in name)
        {
            sb.Append(char.IsLetterOrDigit(c) || c == '_' ? c : '_');
        }
        return sb.ToString();
    }
}
