using System.Text;
using Microsoft.CodeAnalysis;

namespace SQLite.Framework.SourceGenerator;

/// <summary>
/// Writes one method per entity and one method per Select result, plus the
/// <c>UseGeneratedMaterializers</c> extension that adds them to a builder.
/// </summary>
internal static class EntityMaterializerEmitter
{
    public static string Emit(string rootNamespace, IEnumerable<INamedTypeSymbol> entities, IEnumerable<SelectInvocation> selects)
    {
        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS8600, CS8601, CS8602, CS8603, CS8604");
        sb.AppendLine("#pragma warning disable IL2072");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using SQLite.Framework;");
        sb.AppendLine("using SQLite.Framework.Enums;");
        sb.AppendLine("using SQLite.Framework.Internals.Models;");
        sb.AppendLine();
        sb.Append("namespace ").AppendLine(rootNamespace);
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Generated entity and select materializers. Populated onto a builder via <see cref=\"SQLiteFrameworkGeneratedMaterializers.UseGeneratedMaterializers\"/>.</summary>");
        sb.AppendLine("    internal static class SQLiteFrameworkGeneratedMaterializers");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>Registers every emitted materializer onto <paramref name=\"builder\"/>.</summary>");
        sb.AppendLine("        internal static SQLiteOptionsBuilder UseGeneratedMaterializers(this SQLiteOptionsBuilder builder)");
        sb.AppendLine("        {");

        List<(INamedTypeSymbol Symbol, string MethodName)> emittedEntities = new();
        int index = 0;
        foreach (INamedTypeSymbol entity in entities)
        {
            if (!CanEmit(entity))
            {
                continue;
            }

            string methodName = $"Materialize_{SanitizeIdentifier(entity.Name)}_{index++}";
            emittedEntities.Add((entity, methodName));
            sb.Append("            builder.EntityMaterializers[typeof(").Append(entity.ToDisplayString()).Append(")] = ").Append(methodName).AppendLine(";");
        }

        StringBuilder selectBodies = new();
        int selectIndex = 0;
        foreach (SelectInvocation sel in selects)
        {
            string methodName = $"Select_{SanitizeIdentifier(sel.ProjectionType.Name)}_{selectIndex}";
            StringBuilder trial = new();
            bool emitted;
            try
            {
                emitted = SelectMaterializerEmitter.TryEmit(trial, methodName, sel.Body, sel.WriterCtx);
            }
            catch
            {
                emitted = false;
            }

            if (emitted)
            {
                selectBodies.Append(trial);
                sb.Append("            builder.SelectMaterializers[")
                    .Append(EscapeStringLiteral(sel.Signature))
                    .Append("] = ").Append(methodName).AppendLine(";");
                selectIndex++;
            }
        }

        sb.AppendLine("            return builder;");
        sb.AppendLine("        }");
        sb.AppendLine();

        foreach ((INamedTypeSymbol entity, string methodName) in emittedEntities)
        {
            EmitMaterializer(sb, entity, methodName);
        }

        sb.Append(selectBodies);

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string EscapeStringLiteral(string value)
    {
        StringBuilder sb = new(value.Length + 2);
        sb.Append('"');
        foreach (char c in value)
        {
            switch (c)
            {
                case '\\': sb.Append("\\\\"); break;
                case '"': sb.Append("\\\""); break;
                case '\n': sb.Append("\\n"); break;
                case '\r': sb.Append("\\r"); break;
                case '\t': sb.Append("\\t"); break;
                default: sb.Append(c); break;
            }
        }
        sb.Append('"');
        return sb.ToString();
    }

    private static bool CanEmit(INamedTypeSymbol entity)
    {
        if (entity.IsAbstract || entity.IsStatic || entity.TypeKind != TypeKind.Class)
        {
            return false;
        }

        bool hasParameterlessCtor = false;
        foreach (IMethodSymbol ctor in entity.InstanceConstructors)
        {
            if (ctor.DeclaredAccessibility == Accessibility.Public && ctor.Parameters.Length == 0)
            {
                hasParameterlessCtor = true;
                break;
            }
        }

        if (!hasParameterlessCtor)
        {
            return false;
        }

        foreach (ISymbol member in entity.GetMembers())
        {
            if (member is not IPropertySymbol prop)
            {
                continue;
            }

            if (prop.IsStatic || prop.IsIndexer || prop.SetMethod == null)
            {
                continue;
            }

            if (prop.DeclaredAccessibility != Accessibility.Public)
            {
                continue;
            }

            if (!IsSupportedPropertyType(prop.Type))
            {
                return false;
            }
        }

        return true;
    }

    private static bool IsSupportedPropertyType(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol named && named.IsGenericType && named.ConstructedFrom.SpecialType == SpecialType.System_Nullable_T)
        {
            type = named.TypeArguments[0];
        }

        switch (type.SpecialType)
        {
            case SpecialType.System_Boolean:
            case SpecialType.System_Byte:
            case SpecialType.System_SByte:
            case SpecialType.System_Int16:
            case SpecialType.System_UInt16:
            case SpecialType.System_Int32:
            case SpecialType.System_UInt32:
            case SpecialType.System_Int64:
            case SpecialType.System_UInt64:
            case SpecialType.System_Single:
            case SpecialType.System_Double:
            case SpecialType.System_Decimal:
            case SpecialType.System_Char:
            case SpecialType.System_String:
            case SpecialType.System_DateTime:
                return true;
        }

        if (type.TypeKind == TypeKind.Enum)
        {
            return true;
        }

        string fullName = type.ToDisplayString();
        return fullName is "System.DateTimeOffset"
            or "System.TimeSpan"
            or "System.DateOnly"
            or "System.TimeOnly"
            or "System.Guid"
            or "byte[]";
    }

    private static void EmitMaterializer(StringBuilder sb, INamedTypeSymbol entity, string methodName)
    {
        string typeName = entity.ToDisplayString();
        sb.Append("        private static object ").Append(methodName).AppendLine("(SQLite.Framework.Models.SQLiteQueryContext ctx)");
        sb.AppendLine("        {");

        List<IPropertySymbol> requiredProps = new();
        foreach (ISymbol member in entity.GetMembers())
        {
            if (member is IPropertySymbol prop && prop.IsRequired && !prop.IsStatic && prop.SetMethod != null)
            {
                requiredProps.Add(prop);
            }
        }

        if (requiredProps.Count == 0)
        {
            sb.Append("            ").Append(typeName).AppendLine(" result = new();");
        }
        else
        {
            sb.Append("            ").Append(typeName).AppendLine(" result = new()");
            sb.AppendLine("            {");
            for (int i = 0; i < requiredProps.Count; i++)
            {
                IPropertySymbol req = requiredProps[i];
                sb.Append("                ").Append(req.Name).Append(" = default");
                if (req.Type.IsReferenceType || req.Type.NullableAnnotation == NullableAnnotation.Annotated)
                {
                    sb.Append("!");
                }
                sb.AppendLine(i == requiredProps.Count - 1 ? "" : ",");
            }
            sb.AppendLine("            };");
        }
        sb.AppendLine("            var reader = ctx.Reader!;");
        sb.AppendLine("            var columns = ctx.Columns!;");

        foreach (ISymbol member in entity.GetMembers())
        {
            if (member is not IPropertySymbol prop)
            {
                continue;
            }

            if (prop.IsStatic || prop.IsIndexer || prop.SetMethod == null || prop.DeclaredAccessibility != Accessibility.Public)
            {
                continue;
            }

            string propName = prop.Name;
            string propTypeDisplay = prop.Type.ToDisplayString();

            sb.Append("            if (columns.TryGetValue(\"").Append(propName).AppendLine("\", out int idx_" + propName + "))");
            sb.AppendLine("            {");
            sb.Append("                object? value_").Append(propName).Append(" = reader.GetValue(idx_").Append(propName).Append(", reader.GetColumnType(idx_").Append(propName).Append("), typeof(").Append(StripNullable(propTypeDisplay)).AppendLine("));");
            sb.Append("                if (value_").Append(propName).AppendLine(" != null)");
            sb.AppendLine("                {");
            sb.Append("                    result.").Append(propName).Append(" = (").Append(propTypeDisplay).Append(")value_").Append(propName).AppendLine("!;");
            sb.AppendLine("                }");
            sb.AppendLine("            }");
        }

        sb.AppendLine("            return result;");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static string StripNullable(string displayType)
    {
        if (displayType.EndsWith("?"))
        {
            return displayType.Substring(0, displayType.Length - 1);
        }
        return displayType;
    }

    private static string SanitizeIdentifier(string name)
    {
        StringBuilder sb = new(name.Length);
        foreach (char c in name)
        {
            sb.Append(char.IsLetterOrDigit(c) || c == '_' ? c : '_');
        }
        return sb.ToString();
    }
}
