using System.Text;
using Microsoft.CodeAnalysis;

namespace SQLite.Framework.SourceGenerator;

/// <summary>
/// Writes one method per entity and one method per Select result, plus the
/// <c>UseGeneratedMaterializers</c> extension that adds them to a builder.
/// </summary>
internal static class EntityMaterializerEmitter
{
    public static string Emit(string rootNamespace, IEnumerable<INamedTypeSymbol> entities, IEnumerable<SelectInvocation> selects, IEnumerable<(GroupByKeyInvocation Invocation, SemanticModel Model)> groupKeys, HashSet<(INamedTypeSymbol, string)> nestedInitSet)
    {
        HashSet<INamedTypeSymbol> entitySet = new(entities, SymbolEqualityComparer.Default);

        StringBuilder sb = new();
        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("#pragma warning disable CS8600, CS8601, CS8602, CS8603, CS8604, CS8605");
        sb.AppendLine("#pragma warning disable IL2026, IL2057, IL2067, IL2070, IL2072, IL2075, IL2077, IL2080, IL2087, IL2090");
        sb.AppendLine("using System;");
        sb.AppendLine("using System.Collections.Generic;");
        sb.AppendLine("using System.Reflection;");
        sb.AppendLine("using SQLitePCL;");
        sb.AppendLine("using SQLite.Framework;");
        sb.AppendLine("using SQLite.Framework.Enums;");
        sb.AppendLine("using SQLite.Framework.Internals.Models;");
        sb.AppendLine();
        sb.Append("namespace ").AppendLine(rootNamespace);
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Generated entity and select materializers. Populated onto a builder via <see cref=\"SQLiteFrameworkGeneratedMaterializers.UseGeneratedMaterializers\"/>.</summary>");
        sb.AppendLine("    internal static class SQLiteFrameworkGeneratedMaterializers");
        sb.AppendLine("    {");
        sb.AppendLine("        /// <summary>Registers every emitted materializer onto <paramref name=\"builder\"/>.</summary>");
        sb.AppendLine("        internal static SQLiteOptionsBuilder UseGeneratedMaterializers(this SQLiteOptionsBuilder builder)");
        sb.AppendLine("        {");

        List<(INamedTypeSymbol Symbol, string MethodName, EmitStrategy Strategy)> emittedEntities = new();
        int index = 0;
        foreach (INamedTypeSymbol entity in entitySet)
        {
            if (!TryGetEmitStrategy(entity, out EmitStrategy strategy))
            {
                continue;
            }

            string methodName = $"Materialize_{SanitizeIdentifier(entity.Name)}_{index++}";
            emittedEntities.Add((entity, methodName, strategy));

            switch (strategy)
            {
                case EmitStrategy.Direct:
                    sb.Append("            builder.EntityMaterializers[typeof(").Append(entity.ToDisplayString()).Append(")] = ").Append(methodName).AppendLine(";");
                    EntityColumnWriterEmitter.EmitRegistration(sb, entity, methodName);
                    break;
                case EmitStrategy.Reflection:
                    {
                        string typeField = $"s_type_{methodName}";
                        sb.Append("            builder.EntityMaterializers[").Append(typeField).Append("] = ").Append(methodName).AppendLine(";");
                        break;
                    }
                case EmitStrategy.Anonymous:
                    {
                        string typeField = $"s_type_{methodName}";
                        sb.Append("            builder.EntityMaterializers[").Append(typeField).Append("] = ").Append(methodName).AppendLine(";");
                        break;
                    }
            }
        }

        StringBuilder selectBodies = new();
        int selectIndex = 0;
        foreach (SelectInvocation sel in selects)
        {
            string methodName = $"Select_{SanitizeIdentifier(sel.ProjectionType.Name)}_{selectIndex}";
            StringBuilder trial = new();
            bool emitted;
            try
            {
                emitted = SelectMaterializerEmitter.TryEmit(trial, methodName, sel.Body, sel.WriterCtx);
            }
            catch
            {
                emitted = false;
            }

            if (emitted)
            {
                selectBodies.Append(trial);
                sb.Append("            builder.SelectMaterializers[")
                    .Append(EscapeStringLiteral(sel.Signature))
                    .Append("] = ").Append(methodName).AppendLine(";");
                selectIndex++;
            }
        }

        StringBuilder groupKeyBodies = new();
        int groupKeyIndex = 0;
        foreach ((GroupByKeyInvocation invocation, SemanticModel model) in groupKeys)
        {
            string methodName = $"GroupKey_{SanitizeIdentifier(invocation.KeyType.Name)}_{groupKeyIndex}";
            StringBuilder trial = new();
            bool emitted;
            try
            {
                emitted = GroupByKeyMaterializerEmitter.TryEmit(trial, methodName, invocation, model);
            }
            catch
            {
                emitted = false;
            }

            if (emitted)
            {
                groupKeyBodies.Append(trial);
                sb.Append("            builder.GroupByKeyMaterializers[")
                    .Append(EscapeStringLiteral(invocation.Signature))
                    .Append("] = ").Append(methodName).AppendLine(";");
                groupKeyIndex++;
            }
        }

        sb.AppendLine("            return builder;");
        sb.AppendLine("        }");
        sb.AppendLine();

        foreach ((INamedTypeSymbol entity, string methodName, EmitStrategy strategy) in emittedEntities)
        {
            switch (strategy)
            {
                case EmitStrategy.Direct:
                    EmitMaterializer(sb, entity, methodName, entitySet, nestedInitSet);
                    EntityColumnWriterEmitter.EmitWriters(sb, entity, methodName);
                    break;
                case EmitStrategy.Reflection:
                    EmitReflectionMaterializer(sb, entity, methodName, entitySet, nestedInitSet);
                    break;
                case EmitStrategy.Anonymous:
                    EmitAnonymousMaterializer(sb, entity, methodName);
                    break;
            }
        }

        sb.Append(selectBodies);
        sb.Append(groupKeyBodies);

        sb.AppendLine("    }");
        sb.AppendLine("}");
        return sb.ToString();
    }

    private static string EscapeStringLiteral(string value)
    {
        StringBuilder sb = new(value.Length + 2);
        sb.Append('"');
        foreach (char c in value)
        {
            switch (c)
            {
                case '\\': sb.Append("\\\\"); break;
                case '"': sb.Append("\\\""); break;
                case '\n': sb.Append("\\n"); break;
                case '\r': sb.Append("\\r"); break;
                case '\t': sb.Append("\\t"); break;
                default: sb.Append(c); break;
            }
        }
        sb.Append('"');
        return sb.ToString();
    }

    private enum EmitStrategy
    {
        Direct,
        Reflection,
        Anonymous,
    }

    private static bool TryGetEmitStrategy(INamedTypeSymbol entity, out EmitStrategy strategy)
    {
        strategy = EmitStrategy.Direct;

        if (entity.IsAbstract || entity.IsStatic || entity.TypeKind != TypeKind.Class)
        {
            return false;
        }

        if (entity.IsAnonymousType)
        {
            foreach (IPropertySymbol anonProp in entity.GetMembers().OfType<IPropertySymbol>())
            {
                if (!IsEmittablePropertyType(anonProp.Type))
                {
                    return false;
                }
                ITypeSymbol stripped = StripNullableSymbol(anonProp.Type);
                if (!IsReachableFromGeneratedCode(stripped))
                {
                    return false;
                }
            }

            strategy = EmitStrategy.Anonymous;
            return true;
        }

        bool hasAnyParameterlessCtor = false;
        bool hasPublicParameterlessCtor = false;
        foreach (IMethodSymbol ctor in entity.InstanceConstructors)
        {
            if (ctor.Parameters.Length == 0)
            {
                hasAnyParameterlessCtor = true;
                if (ctor.DeclaredAccessibility == Accessibility.Public)
                {
                    hasPublicParameterlessCtor = true;
                }
            }
        }

        if (!hasAnyParameterlessCtor)
        {
            return false;
        }

        bool canNameEntity = IsReachableFromGeneratedCode(entity);
        bool anyPropNeedsReflection = false;

        foreach (IPropertySymbol prop in EnumerateInstanceProperties(entity))
        {
            if (prop.SetMethod == null)
            {
                continue;
            }

            ITypeSymbol propType = prop.Type;
            if (!IsEmittablePropertyType(propType))
            {
                return false;
            }

            if (!IsReachableFromGeneratedCode(propType))
            {
                anyPropNeedsReflection = true;
            }
        }

        strategy = (!canNameEntity || !hasPublicParameterlessCtor || anyPropNeedsReflection)
            ? EmitStrategy.Reflection
            : EmitStrategy.Direct;
        return true;
    }

    private static bool IsReachableFromGeneratedCode(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol named && named.IsGenericType && named.ConstructedFrom.SpecialType == SpecialType.System_Nullable_T)
        {
            type = named.TypeArguments[0];
        }

        if (type is IArrayTypeSymbol array)
        {
            return IsReachableFromGeneratedCode(array.ElementType);
        }

        if (type.TypeKind is TypeKind.TypeParameter or TypeKind.Dynamic or TypeKind.Error)
        {
            return false;
        }

        for (ITypeSymbol? current = type; current != null; current = current.ContainingType)
        {
            if (current is INamedTypeSymbol namedCurrent && namedCurrent.IsFileLocal)
            {
                return false;
            }

            switch (current.DeclaredAccessibility)
            {
                case Accessibility.Public:
                case Accessibility.Internal:
                case Accessibility.ProtectedOrInternal:
                case Accessibility.NotApplicable:
                    continue;
                default:
                    return false;
            }
        }

        return true;
    }

    private static bool IsCompositeUserType(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol nt && nt.IsGenericType && nt.ConstructedFrom.SpecialType == SpecialType.System_Nullable_T)
        {
            type = nt.TypeArguments[0];
        }

        if (IsSupportedPropertyType(type))
        {
            return false;
        }

        if (type.TypeKind == TypeKind.Class && type.SpecialType == SpecialType.None && type.ContainingNamespace?.Name != "System")
        {
            string fullName = type.ToDisplayString();
            if (!fullName.StartsWith("System.") && !fullName.StartsWith("Microsoft."))
            {
                return true;
            }
        }

        return false;
    }

    private static bool IsEmittablePropertyType(ITypeSymbol type)
    {
        if (IsSupportedPropertyType(type))
        {
            return true;
        }

        if (type is INamedTypeSymbol nullable && nullable.IsGenericType && nullable.ConstructedFrom.SpecialType == SpecialType.System_Nullable_T)
        {
            type = nullable.TypeArguments[0];
        }

        return type.TypeKind != TypeKind.Interface && !type.IsAbstract;
    }

    private static bool IsSupportedPropertyType(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol named && named.IsGenericType && named.ConstructedFrom.SpecialType == SpecialType.System_Nullable_T)
        {
            type = named.TypeArguments[0];
        }

        if (type is IArrayTypeSymbol arr && arr.ElementType.SpecialType == SpecialType.System_Byte)
        {
            return true;
        }

        switch (type.SpecialType)
        {
            case SpecialType.System_Boolean:
            case SpecialType.System_Byte:
            case SpecialType.System_SByte:
            case SpecialType.System_Int16:
            case SpecialType.System_UInt16:
            case SpecialType.System_Int32:
            case SpecialType.System_UInt32:
            case SpecialType.System_Int64:
            case SpecialType.System_UInt64:
            case SpecialType.System_Single:
            case SpecialType.System_Double:
            case SpecialType.System_Decimal:
            case SpecialType.System_Char:
            case SpecialType.System_String:
            case SpecialType.System_DateTime:
                return true;
        }

        if (type.TypeKind == TypeKind.Enum)
        {
            return true;
        }

        string fullName = type.ToDisplayString();
        return fullName is "System.DateTimeOffset"
            or "System.TimeSpan"
            or "System.DateOnly"
            or "System.TimeOnly"
            or "System.Guid"
            or "byte[]";
    }

    private static void EmitMaterializer(StringBuilder sb, INamedTypeSymbol entity, string methodName, HashSet<INamedTypeSymbol> entitySet, HashSet<(INamedTypeSymbol, string)> nestedInitSet)
    {
        sb.Append("        private static object ").Append(methodName).AppendLine("(SQLite.Framework.Models.SQLiteQueryContext ctx)");
        sb.AppendLine("        {");
        sb.AppendLine("            var reader = ctx.Reader!;");
        sb.AppendLine("            var columns = ctx.Columns!;");

        int counter = 0;
        EmitEntityProperties(sb, entity, string.Empty, "            ", ref counter, out string resultLocalName, entitySet, nestedInitSet);
        sb.Append("            return ").Append(resultLocalName).AppendLine(";");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void EmitEntityProperties(StringBuilder sb, INamedTypeSymbol entity, string columnPrefix, string indent, ref int counter, out string resultLocalName, HashSet<INamedTypeSymbol> entitySet, HashSet<(INamedTypeSymbol, string)> nestedInitSet)
    {
        List<IPropertySymbol> writableProps = new();
        foreach (IPropertySymbol prop in EnumerateInstanceProperties(entity))
        {
            if (prop.SetMethod != null
                && prop.DeclaredAccessibility == Accessibility.Public)
            {
                writableProps.Add(prop);
            }
        }

        List<string> propValueLocals = new();
        foreach (IPropertySymbol prop in writableProps)
        {
            string propColumn = columnPrefix + prop.Name;
            string localSuffix = counter.ToString();
            counter++;
            string valueLocal = "__val_" + localSuffix;

            INamedTypeSymbol? nestedStripped = StripNullableSymbol(prop.Type) as INamedTypeSymbol;
            bool shouldRecurse = nestedStripped != null
                && nestedStripped.TypeKind == TypeKind.Class
                && entitySet.Contains(nestedStripped)
                && nestedInitSet.Contains((entity, prop.Name));

            if (shouldRecurse && nestedStripped != null)
            {
                EmitEntityProperties(sb, nestedStripped, propColumn + ".", indent, ref counter, out string nestedResult, entitySet, nestedInitSet);
                string propTypeDisplay = prop.Type.ToDisplayString();
                sb.Append(indent).Append(propTypeDisplay).Append(" ").Append(valueLocal).Append(" = ").Append(nestedResult).AppendLine(";");
            }
            else
            {
                EmitSimpleColumnReadLocal(sb, prop.Type, propColumn, valueLocal, localSuffix, indent);
            }

            propValueLocals.Add(valueLocal);
        }

        string typeName = entity.ToDisplayString();
        string resultSuffix = counter.ToString();
        counter++;
        resultLocalName = "__entity_" + resultSuffix;

        sb.Append(indent).Append(typeName).Append(" ").Append(resultLocalName).AppendLine(" = new()");
        sb.Append(indent).AppendLine("{");
        for (int i = 0; i < writableProps.Count; i++)
        {
            sb.Append(indent).Append("    ").Append(writableProps[i].Name).Append(" = ").Append(propValueLocals[i]);
            sb.AppendLine(i == writableProps.Count - 1 ? "" : ",");
        }
        sb.Append(indent).AppendLine("};");
    }

    private static void EmitSimpleColumnReadLocal(StringBuilder sb, ITypeSymbol propType, string columnName, string valueLocal, string localSuffix, string indent)
    {
        string propTypeDisplay = propType.ToDisplayString();
        string strippedDisplay = StripNullable(propTypeDisplay);
        string safeColumn = columnName.Replace("\"", "\\\"");
        string idxLocal = "__idx_" + localSuffix;
        bool isEnum = StripNullableSymbol(propType).TypeKind == TypeKind.Enum;

        sb.Append(indent).Append(propTypeDisplay).Append(" ").Append(valueLocal).Append(" = default");
        if (propType.IsReferenceType || propType.NullableAnnotation == NullableAnnotation.Annotated)
        {
            sb.Append("!");
        }
        sb.AppendLine(";");
        sb.Append(indent).Append("if (columns.TryGetValue(\"").Append(safeColumn).Append("\", out int ").Append(idxLocal).AppendLine("))");
        sb.Append(indent).AppendLine("{");

        bool isNullable = propType.NullableAnnotation == NullableAnnotation.Annotated || propType.IsReferenceType
            || (propType is INamedTypeSymbol nt && nt.IsGenericType && nt.ConstructedFrom.SpecialType == SpecialType.System_Nullable_T);

        if (!isEnum && SelectMaterializerEmitter.TryGetFastPathAccessor(propType, out string? accessor, out string? cast))
        {
            string castOpen = cast is null ? "" : "(" + cast + ")";
            if (isNullable)
            {
                sb.Append(indent).Append("    if (!reader.IsDBNull(").Append(idxLocal).AppendLine("))");
                sb.Append(indent).AppendLine("    {");
                sb.Append(indent).Append("        ").Append(valueLocal).Append(" = ").Append(castOpen).Append("reader.").Append(accessor).Append("(").Append(idxLocal).AppendLine(");");
                sb.Append(indent).AppendLine("    }");
            }
            else
            {
                sb.Append(indent).Append("    ").Append(valueLocal).Append(" = ").Append(castOpen).Append("reader.").Append(accessor).Append("(").Append(idxLocal).AppendLine(");");
            }
            sb.Append(indent).AppendLine("}");
            return;
        }

        sb.Append(indent).Append("    object? __raw_").Append(localSuffix).Append(" = reader.GetValue(").Append(idxLocal).Append(", reader.GetColumnType(").Append(idxLocal).Append("), typeof(").Append(strippedDisplay).AppendLine("));");
        if (isEnum)
        {
            sb.Append(indent).Append("    if (__raw_").Append(localSuffix).Append(" != null && global::System.Enum.IsDefined(typeof(").Append(strippedDisplay).Append("), __raw_").Append(localSuffix).AppendLine("!))");
        }
        else
        {
            sb.Append(indent).Append("    if (__raw_").Append(localSuffix).AppendLine(" != null)");
        }
        sb.Append(indent).AppendLine("    {");
        sb.Append(indent).Append("        ").Append(valueLocal).Append(" = (").Append(propTypeDisplay).Append(")__raw_").Append(localSuffix).AppendLine("!;");
        sb.Append(indent).AppendLine("    }");
        sb.Append(indent).AppendLine("}");
    }

    private static void EmitReflectionMaterializer(StringBuilder sb, INamedTypeSymbol entity, string methodName, HashSet<INamedTypeSymbol> entitySet, HashSet<(INamedTypeSymbol, string)> nestedInitSet)
    {
        string typeField = $"s_type_{methodName}";
        string metadataName = GetMetadataFullName(entity);
        string assemblyName = entity.ContainingAssembly?.Name ?? string.Empty;
        string qualifiedName = metadataName + ", " + assemblyName;

        sb.Append("        private static readonly global::System.Type ").Append(typeField)
            .Append(" = global::System.Type.GetType(").Append(EscapeStringLiteral(qualifiedName))
            .AppendLine(", throwOnError: true)!;");

        List<IPropertySymbol> writableProps = new();
        foreach (IPropertySymbol prop in EnumerateInstanceProperties(entity))
        {
            if (prop.SetMethod != null)
            {
                writableProps.Add(prop);
            }
        }

        foreach (IPropertySymbol prop in writableProps)
        {
            sb.Append("        private static readonly global::System.Reflection.PropertyInfo s_prop_").Append(methodName).Append("_").Append(prop.Name)
                .Append(" = ").Append(typeField)
                .Append(".GetProperty(\"").Append(prop.Name).AppendLine("\", global::System.Reflection.BindingFlags.Instance | global::System.Reflection.BindingFlags.Public | global::System.Reflection.BindingFlags.NonPublic)!;");

            ITypeSymbol propStripped = StripNullableSymbol(prop.Type);
            if (!IsReachableFromGeneratedCode(propStripped))
            {
                string propTypeField = $"s_propType_{methodName}_{prop.Name}";
                string propMetadata = propStripped is INamedTypeSymbol named
                    ? GetMetadataFullName(named) + ", " + (named.ContainingAssembly?.Name ?? string.Empty)
                    : propStripped.ToDisplayString();
                sb.Append("        private static readonly global::System.Type ").Append(propTypeField)
                    .Append(" = global::System.Type.GetType(").Append(EscapeStringLiteral(propMetadata))
                    .AppendLine(", throwOnError: true)!;");
            }
        }

        sb.AppendLine();
        sb.Append("        private static object ").Append(methodName).AppendLine("(SQLite.Framework.Models.SQLiteQueryContext ctx)");
        sb.AppendLine("        {");
        sb.AppendLine("            var reader = ctx.Reader!;");
        sb.AppendLine("            var columns = ctx.Columns!;");
        sb.Append("            object result = global::System.Activator.CreateInstance(").Append(typeField).AppendLine(", nonPublic: true)!;");

        int counter = 0;
        foreach (IPropertySymbol prop in writableProps)
        {
            string propName = prop.Name;
            ITypeSymbol propStripped = StripNullableSymbol(prop.Type);
            INamedTypeSymbol? nestedStripped = propStripped as INamedTypeSymbol;
            bool shouldRecurse = nestedStripped != null
                && nestedStripped.TypeKind == TypeKind.Class
                && IsReachableFromGeneratedCode(propStripped)
                && entitySet.Contains(nestedStripped)
                && nestedInitSet.Contains((entity, prop.Name));

            if (shouldRecurse && nestedStripped != null)
            {
                EmitEntityProperties(sb, nestedStripped, propName + ".", "            ", ref counter, out string nestedResult, entitySet, nestedInitSet);
                sb.Append("            s_prop_").Append(methodName).Append("_").Append(propName).Append(".SetValue(result, ").Append(nestedResult).AppendLine(");");
                continue;
            }

            string typeExpression;
            if (IsReachableFromGeneratedCode(propStripped))
            {
                typeExpression = "typeof(" + propStripped.ToDisplayString() + ")";
            }
            else
            {
                typeExpression = $"s_propType_{methodName}_{propName}";
            }

            sb.Append("            if (columns.TryGetValue(\"").Append(propName).AppendLine("\", out int idx_" + propName + "))");
            sb.AppendLine("            {");
            sb.Append("                object? value_").Append(propName).Append(" = reader.GetValue(idx_").Append(propName).Append(", reader.GetColumnType(idx_").Append(propName).Append("), ").Append(typeExpression).AppendLine(");");
            sb.Append("                if (value_").Append(propName).AppendLine(" != null)");
            sb.AppendLine("                {");
            sb.Append("                    s_prop_").Append(methodName).Append("_").Append(propName).Append(".SetValue(result, value_").Append(propName).AppendLine(");");
            sb.AppendLine("                }");
            sb.AppendLine("            }");
        }

        sb.AppendLine("            return result;");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static void EmitAnonymousMaterializer(StringBuilder sb, INamedTypeSymbol entity, string methodName)
    {
        List<IPropertySymbol> props = entity.GetMembers().OfType<IPropertySymbol>().ToList();
        EmitAnonymousMaterializerDirect(sb, entity, methodName, props);
    }

    private static void EmitAnonymousMaterializerDirect(StringBuilder sb, INamedTypeSymbol entity, string methodName, List<IPropertySymbol> props)
    {
        string typeField = $"s_type_{methodName}";

        StringBuilder sample = new();
        sample.Append("new { ");
        for (int i = 0; i < props.Count; i++)
        {
            IPropertySymbol prop = props[i];
            string typeDisplay = prop.Type.ToDisplayString();
            if (i > 0)
            {
                sample.Append(", ");
            }
            sample.Append(prop.Name).Append(" = default(").Append(typeDisplay).Append(")");
            if (prop.Type.IsReferenceType && prop.Type.NullableAnnotation != NullableAnnotation.Annotated)
            {
                sample.Append("!");
            }
        }
        sample.Append(" }");

        sb.Append("        private static readonly global::System.Type ").Append(typeField)
            .Append(" = (").Append(sample.ToString()).AppendLine(").GetType();");
        sb.AppendLine();

        sb.Append("        private static object ").Append(methodName).AppendLine("(SQLite.Framework.Models.SQLiteQueryContext ctx)");
        sb.AppendLine("        {");
        sb.AppendLine("            var reader = ctx.Reader!;");
        sb.AppendLine("            var columns = ctx.Columns!;");

        foreach (IPropertySymbol prop in props)
        {
            string propName = prop.Name;
            string propTypeDisplay = prop.Type.ToDisplayString();
            string strippedDisplay = StripNullableSymbol(prop.Type).ToDisplayString();

            sb.Append("            ").Append(propTypeDisplay).Append(" value_").Append(propName).Append(" = default");
            bool isAnnotatedOrRef = prop.Type.NullableAnnotation == NullableAnnotation.Annotated || prop.Type.IsReferenceType;
            if (isAnnotatedOrRef)
            {
                sb.Append("!");
            }
            sb.AppendLine(";");
            sb.Append("            if (columns.TryGetValue(\"").Append(propName).AppendLine("\", out int idx_" + propName + "))");
            sb.AppendLine("            {");

            bool propIsNullable = isAnnotatedOrRef
                || (prop.Type is INamedTypeSymbol propNt && propNt.IsGenericType && propNt.ConstructedFrom.SpecialType == SpecialType.System_Nullable_T);

            if (SelectMaterializerEmitter.TryGetFastPathAccessor(prop.Type, out string? accessor, out string? cast))
            {
                string castOpen = cast is null ? "" : "(" + cast + ")";
                if (propIsNullable)
                {
                    sb.Append("                if (!reader.IsDBNull(idx_").Append(propName).AppendLine("))");
                    sb.AppendLine("                {");
                    sb.Append("                    value_").Append(propName).Append(" = ").Append(castOpen).Append("reader.").Append(accessor).Append("(idx_").Append(propName).AppendLine(");");
                    sb.AppendLine("                }");
                }
                else
                {
                    sb.Append("                value_").Append(propName).Append(" = ").Append(castOpen).Append("reader.").Append(accessor).Append("(idx_").Append(propName).AppendLine(");");
                }
            }
            else
            {
                sb.Append("                object? raw_").Append(propName).Append(" = reader.GetValue(idx_").Append(propName).Append(", reader.GetColumnType(idx_").Append(propName).Append("), typeof(").Append(strippedDisplay).AppendLine("));");
                sb.Append("                if (raw_").Append(propName).AppendLine(" != null)");
                sb.AppendLine("                {");
                sb.Append("                    value_").Append(propName).Append(" = (").Append(propTypeDisplay).Append(")raw_").Append(propName).AppendLine("!;");
                sb.AppendLine("                }");
            }
            sb.AppendLine("            }");
        }

        sb.Append("            return new { ");
        for (int i = 0; i < props.Count; i++)
        {
            if (i > 0)
            {
                sb.Append(", ");
            }
            sb.Append(props[i].Name).Append(" = value_").Append(props[i].Name);
        }
        sb.AppendLine(" };");
        sb.AppendLine("        }");
        sb.AppendLine();
    }

    private static IEnumerable<IPropertySymbol> EnumerateInstanceProperties(INamedTypeSymbol entity)
    {
        HashSet<string> seen = new(StringComparer.Ordinal);
        for (INamedTypeSymbol? current = entity; current != null && current.SpecialType != SpecialType.System_Object; current = current.BaseType)
        {
            foreach (ISymbol member in current.GetMembers())
            {
                if (member is not IPropertySymbol prop || prop.IsStatic || prop.IsIndexer)
                {
                    continue;
                }

                if (!seen.Add(prop.Name))
                {
                    continue;
                }

                yield return prop;
            }
        }
    }

    private static ITypeSymbol StripNullableSymbol(ITypeSymbol type)
    {
        if (type is INamedTypeSymbol nt && nt.IsGenericType && nt.ConstructedFrom.SpecialType == SpecialType.System_Nullable_T)
        {
            return nt.TypeArguments[0];
        }
        if (type.NullableAnnotation == NullableAnnotation.Annotated && type.IsReferenceType)
        {
            return type.WithNullableAnnotation(NullableAnnotation.NotAnnotated);
        }
        return type;
    }

    private static string GetMetadataFullName(INamedTypeSymbol symbol)
    {
        StringBuilder sb = new();
        AppendMetadataName(sb, symbol);
        return sb.ToString();
    }

    private static void AppendMetadataName(StringBuilder sb, INamedTypeSymbol symbol)
    {
        if (symbol.ContainingType != null)
        {
            AppendMetadataName(sb, symbol.ContainingType);
            sb.Append('+');
        }
        else
        {
            INamespaceSymbol? ns = symbol.ContainingNamespace;
            if (ns is { IsGlobalNamespace: false })
            {
                sb.Append(ns.ToDisplayString()).Append('.');
            }
        }
        sb.Append(symbol.MetadataName);
    }

    private static string StripNullable(string displayType)
    {
        if (displayType.EndsWith("?"))
        {
            return displayType.Substring(0, displayType.Length - 1);
        }
        return displayType;
    }

    private static string SanitizeIdentifier(string name)
    {
        StringBuilder sb = new(name.Length);
        foreach (char c in name)
        {
            sb.Append(char.IsLetterOrDigit(c) || c == '_' ? c : '_');
        }
        return sb.ToString();
    }
}
