name: Run Tests

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        project:
          - SQLite.Framework.Tests
          - SQLite.Framework.Tests.Bundled
          - SQLite.Framework.Tests.Cipher
          - SQLite.Framework.Tests.Base
          - SQLite.Framework.Tests.SourceGenerator
    name: ${{ matrix.project }}
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - name: Setup .NET
        uses: actions/setup-dotnet@v5.3.0
        with:
          dotnet-version: 10.0.x
      - name: Run tests
        run: |
          dotnet run --project Tests/${{ matrix.project }}/${{ matrix.project }}.csproj -c Release \
            -- --report-xunit-junit \
               --report-xunit-junit-filename ${{ matrix.project }}.junit.xml \
               --results-directory TestResults
