name: Run Tests

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        project:
          - SQLite.Framework.Tests
          - SQLite.Framework.Tests.Bundled
          - SQLite.Framework.Tests.Cipher
          - SQLite.Framework.Tests.Base
          - SQLite.Framework.Tests.SourceGenerator
          - SQLite.Framework.Tests.DependencyInjection
          - SQLite.Framework.Tests.AotMigrate
    name: ${{ matrix.project }}
    steps:
      - uses: actions/checkout@v7
        with:
          persist-credentials: false
      - name: Setup .NET
        uses: actions/setup-dotnet@v6.0.0
        with:
          dotnet-version: 10.0.x
      - name: Install Android workload
        run: dotnet workload install android
      - name: Run tests
        if: ${{ matrix.project != 'SQLite.Framework.Tests.AotMigrate' }}
        run: |
          dotnet run --project Tests/${{ matrix.project }}/${{ matrix.project }}.csproj -c Release \
            -- --report-xunit-junit \
               --report-xunit-junit-filename ${{ matrix.project }}.junit.xml \
               --results-directory TestResults
      - name: Publish native tests
        if: ${{ matrix.project == 'SQLite.Framework.Tests.AotMigrate' }}
        run: dotnet publish Tests/${{ matrix.project }}/${{ matrix.project }}.csproj -c Release
      - name: Run native tests
        if: ${{ matrix.project == 'SQLite.Framework.Tests.AotMigrate' }}
        run: |
          Tests/${{ matrix.project }}/bin/Release/net10.0/linux-x64/publish/${{ matrix.project }} \
            --report-xunit-junit \
            --report-xunit-junit-filename ${{ matrix.project }}.junit.xml \
            --results-directory TestResults
